### ISSUE TITLE
Clean Zulip won't start: [boto] Caught exception reading instance data

### ISSUE THREAD

**Issue by xificurC** [zulip/docker-zulip#155]
I did a clean `docker-compose pull && docker-compose up -d` and the Zulip container keeps dying. I tried to build the image from `master`, same results. Output of `docker logs docker-zulip_zulip_1`

```
=== Begin Initial Configuration Phase ===
Preparing and linking the uploads folder ...
Prepared and linked the uploads directory.
Executing nginx configuration ...
Nginx configuration succeeded.
Generating self-signed certificates ...
+ KEYFILE=/etc/ssl/private/zulip.key
+ CERTFILE=/etc/ssl/certs/zulip.combined-chain.crt
+ '[' -n '' ']'
+ '[' -z '' ']'
+ '[' -e /etc/ssl/private/zulip.key ']'
+ '[' -e /etc/ssl/certs/zulip.combined-chain.crt ']'
+ rm -f /etc/ssl/private/zulip.key /etc/ssl/certs/zulip.combined-chain.crt
++ mktemp
+ config=/tmp/tmp.RUJWqzxpCO
+ trap 'rm -f "$config"' EXIT
+ cat
+ apt-get install -y openssl
Reading package lists...
Building dependency tree...
Reading state information...
openssl is already the newest version (1.0.2g-1ubuntu4.13).
openssl set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ openssl req -new -x509 -config /tmp/tmp.RUJWqzxpCO -days 3650 -nodes -sha256 -out /etc/ssl/certs/zulip.combined-chain.crt -keyout /etc/ssl/private/zulip.key
Generating a 2048 bit RSA private key
........................+++
............+++
writing new private key to '/etc/ssl/private/zulip.key'
-----
+ chmod 644 /etc/ssl/certs/zulip.combined-chain.crt
+ chmod 640 /etc/ssl/private/zulip.key
+ rm -f /tmp/tmp.RUJWqzxpCO
Self-signed certificate generation succeeded.
Certificates configuration succeeded.
Setting database configuration ...
Setting key "REMOTE_POSTGRES_HOST", type "string" in file "/etc/zulip/settings.py".
Setting key "REMOTE_POSTGRES_SSLMODE", type "string" in file "/etc/zulip/settings.py".
Database configuration succeeded.
Setting Zulip secrets ...
Generating Zulip secrets ...
Generated Camo config file /etc/default/camo
Generated new secrets in /etc/zulip/zulip-secrets.conf.
Secrets generation succeeded.
Zulip secrets configuration succeeded.
Activating authentication backends ...
Setting key "AUTHENTICATION_BACKENDS", type "array" in file "/etc/zulip/settings.py".
Adding authentication backend "EmailAuthBackend".
Authentication backend activation succeeded.
Executing Zulip configuration ...
Setting key "EXTERNAL_HOST", type "string" in file "/etc/zulip/settings.py".
Empty var for key "EMAIL_HOST".
Setting key "ZULIP_ADMINISTRATOR", type "string" in file "/etc/zulip/settings.py".
Setting key "REDIS_HOST", type "string" in file "/etc/zulip/settings.py".
Setting key "RABBITMQ_HOST", type "string" in file "/etc/zulip/settings.py".
Setting key "EMAIL_HOST_USER", type "string" in file "/etc/zulip/settings.py".
Setting key "MEMCACHED_LOCATION", type "string" in file "/etc/zulip/settings.py".
Setting key "EMAIL_USE_SSL", type "bool" in file "/etc/zulip/settings.py".
Setting key "EMAIL_USE_TLS", type "bool" in file "/etc/zulip/settings.py".
Setting key "EMAIL_PORT", type "integer" in file "/etc/zulip/settings.py".
Zulip configuration succeeded.
Auto backup enabled.
=== End Initial Configuration Phase ===
=== Begin Bootstrap Phase ===
Waiting for database server to allow connections ...
Executing Zulip first start init ...
+++ readlink -f /home/zulip/deployments/current/scripts/setup/initialize-database
++ dirname /home/zulip/deployments/2018-08-30-13-08-33/scripts/setup/initialize-database
+ THIS_DIR=/home/zulip/deployments/2018-08-30-13-08-33/scripts/setup
+ cd /home/zulip/deployments/2018-08-30-13-08-33/scripts/setup/../..
+ ./manage.py checkconfig
+ ./manage.py migrate --noinput
Operations to perform:
  Apply all migrations: analytics, auth, confirmation, contenttypes, otp_static, otp_totp, sessions, sites, social_django, two_factor, zerver
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying zerver.0001_initial... OK
  Applying zerver.0029_realm_subdomain... OK
  Applying zerver.0030_realm_org_type... OK
  Applying zerver.0031_remove_system_avatar_source... OK
  Applying zerver.0032_verify_all_medium_avatar_images... OK
  Applying zerver.0033_migrate_domain_to_realmalias... OK
  Applying zerver.0034_userprofile_enable_online_push_notifications... OK
  Applying zerver.0035_realm_message_retention_period_days... OK
  Applying zerver.0036_rename_subdomain_to_string_id... OK
  Applying zerver.0037_disallow_null_string_id... OK
  Applying zerver.0038_realm_change_to_community_defaults... OK
  Applying zerver.0039_realmalias_drop_uniqueness... OK
  Applying zerver.0040_realm_authentication_methods... OK
  Applying zerver.0041_create_attachments_for_old_messages... OK
  Applying zerver.0042_attachment_file_name_length... OK
  Applying zerver.0043_realm_filter_validators... OK
  Applying zerver.0044_reaction... OK
  Applying zerver.0045_realm_waiting_period_threshold... OK
  Applying zerver.0046_realmemoji_author... OK
  Applying zerver.0047_realm_add_emoji_by_admins_only... OK
  Applying zerver.0048_enter_sends_default_to_false... OK
  Applying zerver.0049_userprofile_pm_content_in_desktop_notifications... OK
  Applying zerver.0050_userprofile_avatar_version... OK
  Applying analytics.0001_initial... OK
  Applying analytics.0002_remove_huddlecount... OK
  Applying analytics.0003_fillstate... OK
  Applying analytics.0004_add_subgroup... OK
  Applying analytics.0005_alter_field_size... OK
  Applying analytics.0006_add_subgroup_to_unique_constraints... OK
  Applying analytics.0007_remove_interval... OK
  Applying analytics.0008_add_count_indexes... OK
  Applying analytics.0009_remove_messages_to_stream_stat... OK
  Applying analytics.0010_clear_messages_sent_values... OK
  Applying analytics.0011_clear_analytics_tables... OK
  Applying analytics.0012_add_on_delete... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying zerver.0051_realmalias_add_allow_subdomains... OK
  Applying zerver.0052_auto_fix_realmalias_realm_nullable... OK
  Applying zerver.0053_emailchangestatus... OK
  Applying zerver.0054_realm_icon... OK
  Applying zerver.0055_attachment_size... OK
  Applying zerver.0056_userprofile_emoji_alt_code... OK
  Applying zerver.0057_realmauditlog... OK
  Applying zerver.0058_realm_email_changes_disabled... OK
  Applying zerver.0059_userprofile_quota... OK
2018-08-30 13:14:55.774 ERR  [boto] Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/boto/utils.py", line 217, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
2018-08-30 13:14:55.806 ERR  [boto] Unable to read instance data, giving up
Traceback (most recent call last):
  File "./manage.py", line 36, in <module>
    execute_from_command_line(sys.argv)
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/zulip/deployments/2018-08-30-13-08-33/zerver/migrations/0060_move_avatars_to_be_uid_based.py", line 56, in move_avatars_to_be_uid_based
    conn = S3Connection(settings.S3_KEY, settings.S3_SECRET_KEY)
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/boto/s3/connection.py", line 194, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/home/zulip/deployments/2018-08-30-13-08-33/zulip-py3-venv/lib/python3.5/site-packages/boto/auth.py", line 1021, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
  Applying zerver.0060_move_avatars_to_be_uid_based...Zulip first start database initi failed in "initialize-database" exit code 1. Exiting.
```

**Comment by timabbott** [comment]
@xificurC try setting the `LOCAL_UPLOADS_DIR` setting -- it looks like it's not using the default value for that and thus trying to use the S3 backend instead...

**Comment by timabbott** [comment]
I think we just need the default of `/home/zulip/uploads` (inside the container).  The fix to this is going to be having the `settings.py` file copied from `/home/zulip/deployments/current/zproject/prod_settings_template.py`.  I'm testing that now.

**Comment by timabbott** [comment]
I believe the bug is fixed properly with my last commit.  I'll post a new image hopefully today.

**Comment by timabbott** [comment]
I just posted 1.9.0-rc2-0; can you confirm that resolves this issue for you?

**Comment by xificurC** [comment]
I rebuilt from `master` yesterday, sorry I didn't test the released version. `LOCAL_UPLOADS_DIR` now does show up in the default `settings.py`, so this issue is resolved

**Comment by timabbott** [comment]
Great, thanks for the confirmation!
