### ISSUE TITLE
Migration ERROR: cannot CREATE INDEX "zerver_userprofile" because it has pending trigger events

### ISSUE THREAD

**Issue by nil4** [zulip/docker-zulip#160]
I'm trying to migrate from `galexrt/zulip:1.8.0-1` to `zulip/docker-zulip:1.9.0-rc2-0`, preserving the existing data. I followed the [upgrading from `galexrt/docker`](https://github.com/zulip/docker-zulip#upgrading-from-the-old-galexrtdocker-zulip) guide and converted the Postgres data successfully.

If I bootstrap with an empty `/opt/docker/zulip` folder, all migrations run and Zulip starts up correctly, but the previous data is lost.

When I attempt to bootstrap with the converted Postgres data in place at `/opt/docker/zulip/postgresql/data`, the migration fails reproducibly with the following log:

```
zulip_1      | Zulip configuration succeeded.
zulip_1      | Auto backup enabled.
zulip_1      | === End Initial Configuration Phase ===
zulip_1      | === Begin Bootstrap Phase ===
zulip_1      | Waiting for database server to allow connections ...
zulip_1      | Executing Zulip first start init ...
zulip_1      | +++ readlink -f /home/zulip/deployments/current/scripts/setup/initialize-database
zulip_1      | ++ dirname /home/zulip/deployments/2018-09-01-00-53-13/scripts/setup/initialize-database
zulip_1      | + THIS_DIR=/home/zulip/deployments/2018-09-01-00-53-13/scripts/setup
zulip_1      | + cd /home/zulip/deployments/2018-09-01-00-53-13/scripts/setup/../..
zulip_1      | + ./manage.py checkconfig
zulip_1      | + ./manage.py migrate --noinput
zulip_1      | Operations to perform:
zulip_1      |   Apply all migrations: analytics, auth, confirmation, contenttypes, otp_static, otp_totp, sessions, sites, social_django, two_factor, zerver
zulip_1      | Running migrations:
database_1   | 2018-09-19 16:24:35.721 UTC [30] ERROR:  cannot CREATE INDEX "zerver_userprofile" because it has pending trigger events
database_1   | 2018-09-19 16:24:35.721 UTC [30] STATEMENT:  CREATE INDEX "zerver_userprofile_delivery_email_d4f2145b" ON "zerver_userprofile" ("delivery_email")
zulip_1      |   Applying zerver.0174_userprofile_delivery_email...Traceback (most recent call last):
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
zulip_1      |     return self.cursor.execute(sql, params)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zerver/lib/db.py", line 33, in execute
zulip_1      |     return wrapper_execute(self, super().execute, query, vars)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zerver/lib/db.py", line 20, in wrapper_execute
zulip_1      |     return action(sql, params)
zulip_1      | psycopg2.OperationalError: cannot CREATE INDEX "zerver_userprofile" because it has pending trigger events
zulip_1      |
zulip_1      |
zulip_1      | The above exception was the direct cause of the following exception:
zulip_1      |
zulip_1      | Traceback (most recent call last):
zulip_1      |   File "./manage.py", line 36, in <module>
zulip_1      |     execute_from_command_line(sys.argv)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
zulip_1      |     utility.execute()
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
zulip_1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
zulip_1      |     self.execute(*args, **cmd_options)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
zulip_1      |     output = self.handle(*args, **options)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
zulip_1      |     fake_initial=fake_initial,
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
zulip_1      |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
zulip_1      |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
zulip_1      |     state = migration.apply(state, schema_editor)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 109, in __exit__
zulip_1      |     self.execute(sql)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 136, in execute
zulip_1      |     cursor.execute(sql, params)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
zulip_1      |     return self.cursor.execute(sql, params)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
zulip_1      |     six.reraise(dj_exc_type, dj_exc_value, traceback)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
zulip_1      |     raise value.with_traceback(tb)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
zulip_1      |     return self.cursor.execute(sql, params)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zerver/lib/db.py", line 33, in execute
zulip_1      |     return wrapper_execute(self, super().execute, query, vars)
zulip_1      |   File "/home/zulip/deployments/2018-09-01-00-53-13/zerver/lib/db.py", line 20, in wrapper_execute
zulip_1      |     return action(sql, params)
zulip_1      | django.db.utils.OperationalError: cannot CREATE INDEX "zerver_userprofile" because it has pending trigger events
zulip_1      |
zulip_1      | Zulip first start database initi failed in "initialize-database" exit code 1. Exiting.
docker-zulip_zulip_1 exited with code 1
```

I am stuck here, and would really appreciate any ideas on how to more forward. Thanks!

**Comment by timabbott** [comment]
I should also note that the code seems to be trying to run the very first/initial migration, which it should only be doing on an EMPTY database.  So I think you're not correctly putting the data in place.  The issue is almost certainly that the postgres versions are different between the two `docker-zulip` versions, and you haven't done an appropriate process to migrate the postgres data between versions before putting it in the `/opt/docker` directories.  As a result, postgres 10 sees an empty postgres 10 database, since the data structure for postgres has the postgres version in directory names.  

@galexrt any ideas as to where something might have been missed in following the upgrade instructions?

**Comment by nil4** [comment]
@timabbott thank you, I really appreciate the feedback. It does look like a full migration indeed; not sure what's going on to be honest. I'll take a closer look when I have a chance.
