### ISSUE TITLE
Can't migrate to zulip 1.9.0

### ISSUE THREAD

**Issue by zingmars** [zulip/docker-zulip#163]
Upgrade to zulip 1.9.0-0 (from 1.8.1-0) using the version from docker hub fails. The old image was from https://hub.docker.com/r/galexrt/zulip/ if that changes anything.
```
Attaching to zulip_memcached_1, zulip_rabbitmq_1, zulip_zulip_1, zulip_redis_1, zulip_database_1
zulip_1      | === Begin Initial Configuration Phase ===
redis_1      | Starting redis-server...
database_1   | 2018-11-09 15:15:15.017 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
zulip_1      | Preparing and linking the uploads folder ...
database_1   | 2018-11-09 15:15:15.017 UTC [1] LOG:  listening on IPv6 address "::", port 5432
redis_1      | 1:C 09 Nov 15:15:13.724 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1      | 1:C 09 Nov 15:15:13.724 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
zulip_1      | Prepared and linked the uploads directory.
redis_1      | 1:C 09 Nov 15:15:13.724 # Configuration loaded
zulip_1      | Executing nginx configuration ...
redis_1      |                 _._
zulip_1      | Nginx configuration succeeded.
redis_1      |            _.-``__ ''-._
redis_1      |       _.-``    `.  `_.  ''-._           Redis 4.0.9 (00000000/0) 64 bit
redis_1      |   .-`` .-```.  ```\/    _.,_ ''-._
zulip_1      | Certificates configuration succeeded.
redis_1      |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
zulip_1      | Setting database configuration ...
redis_1      |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1      |   `-._    `-._  `-./  _.-'    _.-'
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'
zulip_1      | Setting key "REMOTE_POSTGRES_HOST", type "string" in file "/etc/zulip/settings.py".
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1      |  |    `-._`-._        _.-'_.-'    |
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1      |       `-._    `-.__.-'    _.-'
redis_1      |           `-._        _.-'
redis_1      |               `-.__.-'
redis_1      |
redis_1      | 1:M 09 Nov 15:15:13.726 # Server initialized
zulip_1      | Setting key "REMOTE_POSTGRES_SSLMODE", type "string" in file "/etc/zulip/settings.py".
redis_1      | 1:M 09 Nov 15:15:13.726 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for
this to take effect.
zulip_1      | Database configuration succeeded.
zulip_1      | Setting Zulip secrets ...
redis_1      | 1:M 09 Nov 15:15:13.726 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1      | 1:M 09 Nov 15:15:13.726 * DB loaded from disk: 0.000 seconds
redis_1      | 1:M 09 Nov 15:15:13.726 * Ready to accept connections
zulip_1      | Secrets already generated/existing.
redis_1      | 1:M 09 Nov 15:15:13.726 * The server is now ready to accept connections at /var/run/redis/redis-server.sock
zulip_1      | Zulip secrets configuration succeeded.
zulip_1      | Activating authentication backends ...
zulip_1      | Setting key "AUTHENTICATION_BACKENDS", type "array" in file "/etc/zulip/settings.py".
zulip_1      | Adding authentication backend "EmailAuthBackend".
zulip_1      | Authentication backend activation succeeded.
zulip_1      | Executing Zulip configuration ...
zulip_1      | Setting key "EXTERNAL_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "ALLOWED_HOSTS", type "array" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "NOREPLY_EMAIL_ADDRESS", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "ZULIP_ADMINISTRATOR", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "REDIS_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "RABBITMQ_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "PUSH_NOTIFICATION_BOUNCER_URL", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_HOST_USER", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "DEFAULT_FROM_EMAIL", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "MEMCACHED_LOCATION", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_USE_SSL", type "bool" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_USE_TLS", type "bool" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "ADMIN_DOMAIN", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_PORT", type "integer" in file "/etc/zulip/settings.py".
zulip_1      | Zulip configuration succeeded.
zulip_1      | Auto backup enabled.
zulip_1      | === End Initial Configuration Phase ===
zulip_1      | === Begin Bootstrap Phase ===
zulip_1      | Waiting for database server to allow connections ...
database_1   | 2018-11-09 15:15:15.107 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1   | 2018-11-09 15:15:15.175 UTC [25] LOG:  database system was shut down at 2018-11-09 15:07:24 UTC
database_1   | 2018-11-09 15:15:15.252 UTC [1] LOG:  database system is ready to accept connections
zulip_1      | Executing Zulip first start init ...
zulip_1      | First Start Init not needed. Continuing.
zulip_1      | Migrating Zulip to new version ...
rabbitmq_1   | 2018-11-09 15:15:15.991 [info] <0.33.0> Application lager started on node 'rabbit@zulip-rabbit'
zulip_1      | Traceback (most recent call last):
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
zulip_1      |     self.connect()
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
zulip_1      |     self.connection = self.get_new_connection(conn_params)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
zulip_1      |     connection = Database.connect(**conn_params)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
zulip_1      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zerver/lib/db.py", line 44, in __init__
zulip_1      |     super().__init__(*args, **kwargs)
zulip_1      | psycopg2.OperationalError: fe_sendauth: no password supplied
zulip_1      |
zulip_1      |
zulip_1      | The above exception was the direct cause of the following exception:
zulip_1      |
zulip_1      | Traceback (most recent call last):
zulip_1      |   File "/home/zulip/deployments/current/manage.py", line 46, in <module>
zulip_1      |     execute_from_command_line(sys.argv)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
zulip_1      |     utility.execute()
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
zulip_1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
zulip_1      |     self.execute(*args, **cmd_options)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
zulip_1      |     output = self.handle(*args, **options)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 83, in handle
zulip_1      |     executor = MigrationExecutor(connection, self.migration_progress_callback)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
zulip_1      |     self.loader = MigrationLoader(self.connection)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
zulip_1      |     self.build_graph()
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/loader.py", line 209, in build_graph
zulip_1      |     self.applied_migrations = recorder.applied_migrations()
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
zulip_1      |     self.ensure_schema()
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
zulip_1      |     if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 254, in cursor
zulip_1      |     return self._cursor()
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 229, in _cursor
zulip_1      |     self.ensure_connection()
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
zulip_1      |     self.connect()
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
zulip_1      |     six.reraise(dj_exc_type, dj_exc_value, traceback)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
zulip_1      |     raise value.with_traceback(tb)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
zulip_1      |     self.connect()
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
zulip_1      |     self.connection = self.get_new_connection(conn_params)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
zulip_1      |     connection = Database.connect(**conn_params)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zulip-py3-venv/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
zulip_1      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
zulip_1      |   File "/home/zulip/deployments/2018-11-07-22-43-54/zerver/lib/db.py", line 44, in __init__
zulip_1      |     super().__init__(*args, **kwargs)
zulip_1      | django.db.utils.OperationalError: fe_sendauth: no password supplied
zulip_1      |
zulip_1      | Zulip migration failed with exit code 1. Exiting.
```

**Comment by timabbott** [comment]
Check out https://github.com/zulip/docker-zulip#upgrading-from-the-old-galexrtdocker-zulip; there's some manual steps needed for that upgrade.

(I suppose we should add a link to those to the "Upgrade notes" section of the main changelog, shouldn't we?)

**Comment by zingmars** [comment]
This happens with `zulip/zulip-postgresql` though. I already did the upgrade when #123 was raised.

**Comment by timabbott** [comment]
Well, what I thought was going on here is that you're connecting to a postgres database container that is uninitialized; but reading more closely, it looks like your Zulip/Django `settings.py` file doesn't have a postgres password set (hence the "no password supplied" error)... Can you look into what's going on with your `SECRETS_postgres_password` setting?

**Comment by zingmars** [comment]
It didn't exist because previously the DB_HOST, DB_PASSWORD etc variables set these passwords. I suppose I should've diffed the new docker-compose instead of just going over it, hah. Might want to add this to the migration instructions though.

Next up is zulip-thumbor. I seem to have a similar issue to #153, but the error in the thumbor's log file is different - 
```
Traceback (most recent call last):
  File "/home/zulip/deployments/current/zulip-thumbor-venv/bin/thumbor", line 11, in <module>
    sys.exit(main())
  File "/srv/zulip-venv-cache/890ced270adac8406802ba25797517e3250e67d8/zulip-thumbor-venv/local/lib/python2.7/site-packages/thumbor/server.py", line 139, in main
    validate_config(config, server_parameters)
  File "/srv/zulip-venv-cache/890ced270adac8406802ba25797517e3250e67d8/zulip-thumbor-venv/local/lib/python2.7/site-packages/thumbor/server.py", line 84, in validate_config
    'Please provide one using the conf file or a security key file.')
RuntimeError: No security key was found for this instance of thumbor. Please provide one using the conf file or a security key file.
```

**Comment by timabbott** [comment]
@zingmars yeah, thumbor is not used by default (though it probably will be in the next release).  To fix this, you should just need to run `scripts/setup/generate_secrets.py` (which will add any secrets that are added in the new version).  I think the fix is we should modify `secretsConfiguration` in `entrypoint.sh` to run that command unconditionally (the simplesy approach might be to just run it at the end, just before the `echo` statement there).  Can you try testing that?  I can make a PR if helpful.

**Comment by zingmars** [comment]
Sorry for taking so long to get back to you.
Running `generate_secrets.py` seems to have fixed the error.

**Comment by timabbott** [comment]
Great; but I'm reopening this, since we want to tweak the code to fix new secrets being added for others.
