### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by xiaomingplus** [zulip/docker-zulip#191]
I git clone the docker-zulip git master branch,and run `docker build -t xxxx/zulip .`

after yarn install success there is a error as follow:

```bash
Successfully installed Yarn 1.7.0!
+ sudo mkdir -p /srv/zulip-npm-cache
+ sudo chown 1000:1000 /srv/zulip-npm-cache
Cached version not found! Installing node modules.
+ mkdir -p /srv/zulip-npm-cache/0ebf91dbb99cc9fd889c8c090876d73ed98d8afc
+ cp package.json yarn.lock /srv/zulip-npm-cache/0ebf91dbb99cc9fd889c8c090876d73ed98d8afc
+ /home/zulip/zulip/scripts/lib/cd_exec /srv/zulip-npm-cache/0ebf91dbb99cc9fd889c8c090876d73ed98d8afc /srv/zulip-yarn/bin/yarn install --non-interactive --prefer-offline
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

Error running a subcommand of ./lib/provision.py: /home/zulip/zulip/scripts/lib/cd_exec /srv/zulip-npm-cache/0ebf91dbb99cc9fd889c8c090876d73ed98d8afc /srv/zulip-yarn/bin/yarn install --non-interactive --prefer-offline
Actual error output for the subcommand is just above this.

`yarn install` failed; retrying...
Cached version not found! Installing node modules.
+ mkdir -p /srv/zulip-npm-cache/0ebf91dbb99cc9fd889c8c090876d73ed98d8afc
+ cp package.json yarn.lock /srv/zulip-npm-cache/0ebf91dbb99cc9fd889c8c090876d73ed98d8afc
+ /home/zulip/zulip/scripts/lib/cd_exec /srv/zulip-npm-cache/0ebf91dbb99cc9fd889c8c090876d73ed98d8afc /srv/zulip-yarn/bin/yarn install --non-interactive
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

Error running a subcommand of ./lib/provision.py: /home/zulip/zulip/scripts/lib/cd_exec /srv/zulip-npm-cache/0ebf91dbb99cc9fd889c8c090876d73ed98d8afc /srv/zulip-yarn/bin/yarn install --non-interactive
Actual error output for the subcommand is just above this.

Traceback (most recent call last):
  File "./lib/provision.py", line 384, in main
    setup_node_modules(prefer_offline=True)
  File "/home/zulip/zulip/scripts/lib/node_cache.py", line 70, in setup_node_modules
    copy_modules=copy_modules)
  File "/home/zulip/zulip/scripts/lib/node_cache.py", line 105, in do_yarn_install
    run(cmd, stdout=stdout, stderr=stderr)
  File "/home/zulip/zulip/scripts/lib/zulip_tools.py", line 203, in run
    subprocess.check_call(args, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/zulip/zulip/scripts/lib/cd_exec', '/srv/zulip-npm-cache/0ebf91dbb99cc9fd889c8c090876d73ed98d8afc', '/srv/zulip-yarn/bin/yarn', 'install', '--non-interactive', '--prefer-offline']' returned non-zero exit status -9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lib/provision.py", line 558, in <module>
    sys.exit(main(options))
  File "./lib/provision.py", line 387, in main
    setup_node_modules()
  File "/home/zulip/zulip/scripts/lib/node_cache.py", line 70, in setup_node_modules
    copy_modules=copy_modules)
  File "/home/zulip/zulip/scripts/lib/node_cache.py", line 105, in do_yarn_install
    run(cmd, stdout=stdout, stderr=stderr)
  File "/home/zulip/zulip/scripts/lib/zulip_tools.py", line 203, in run
    subprocess.check_call(args, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/zulip/zulip/scripts/lib/cd_exec', '/srv/zulip-npm-cache/0ebf91dbb99cc9fd889c8c090876d73ed98d8afc', '/srv/zulip-yarn/bin/yarn', 'install', '--non-interactive']' returned non-zero exit status -9

Provisioning failed!

* Look at the traceback(s) above to find more about the errors.
* Resolve the errors or get help on chat.
* If you can fix this yourself, you can re-run tools/provision at any time.
* Logs are here: zulip/var/log/provision.log

The command '/bin/bash -xuo pipefail -c ./tools/provision --production-travis' returned a non-zero code: 1
```

**Comment by timabbott** [comment]
@xiaomingplus I think yarn might actually be failing without an error message.  This could be a problem with your fork, network connectivity, or insufficient system resources to build the third-party `yarn` dependencies.

**Comment by xiaomingplus** [comment]
@timabbott thanks,I use the official version build,I think it maybe a system resources problem,I'll try again.

**Comment by timabbott** [comment]
OK, let me know and close the issue if you confirm that's what's happening.

**Comment by xiaomingplus** [comment]
@timabbott it worked ok! indeed a system resource problem.thanks!
