### ISSUE TITLE
Cant set Environment to Manual (LINK_SETTINGS_TO_DATA and MANUAL_CONFIGURATION)

### ISSUE THREAD

**Issue by Atomique** [zulip/docker-zulip#209]
I just added the environment variables "LINK_SETTINGS_TO_DATA=True" and "MANUAL_CONFIGURATION=True" to change the settings for LDAP Auth - and I get the Error: 

> ImportError: No module named 'zproject.dev_settings'. 

If I set them to false, everything is working normal, I can start the server, login etc. I just want to change the settings.py to setup LDAP - I dont need more. I tried to set the permissions to UID 1000 without any luck. 

Is there another way to configure the settings I am missing maybe?

Error-Message from the Container:

```
=== Begin Bootstrap Phase ===
Waiting for database server to allow connections ...
Executing Zulip first start init ...
First Start Init not needed. Continuing.
Migrating Zulip to new version ...
Traceback (most recent call last):
File "/home/zulip/deployments/current/manage.py", line 40, in <module>
log_management_command(" ".join(sys.argv), settings.MANAGEMENT_LOG_PATH)
File "/home/zulip/deployments/2019-06-20-00-28-26/zulip-py3-venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
self._setup(name)
File "/home/zulip/deployments/2019-06-20-00-28-26/zulip-py3-venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
self._wrapped = Settings(settings_module)
File "/home/zulip/deployments/2019-06-20-00-28-26/zulip-py3-venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 986, in _gcd_import
File "<frozen importlib._bootstrap>", line 969, in _find_and_load
File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 665, in exec_module
File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
File "/home/zulip/deployments/2019-06-20-00-28-26/zproject/settings.py", line 111, in <module>
from .dev_settings import *
ImportError: No module named 'zproject.dev_settings'
Zulip migration failed with exit code 1. Exiting.
```

If you need further information - let me know

I tried the following: 

- Copy the generated File to /data/settings.py and change the permissions
- Copy the generated File to /data/settings/settings.py and change the permissions
- Change the permissions of /data/settings folder with chown -R 1000:1000 settings/

As soon as I set the Values to false and using the auto generated files -> everything works fine. I also tried to start from scratch, deleting the persistant folder data of all zulip-containers - no chance. 

I posted first in issue #129 - but I think this could be another problem - I hope you dont get this as spam - just want to simplify things for you!

_Originally posted by @Atomique in https://github.com/zulip/docker-zulip/issues/129#issuecomment-510076107_

**Comment by timabbott** [comment]
Thanks for the report!  I haven't used this setting myself but hopefully I can find someone willing to investigate.

**Comment by Atomique** [comment]
It's no more needed because I found out, that I can set everything over the environment variables! But if you need further information, I will try to help out.

**Comment by maltokyo** [comment]
This didn't work for me either.  I guess I'll have to go hunting for all of the env variables I need.  Any help with this @Atomique ?  Thank you!

**Comment by timabbott** [comment]
We just fixed a bug in zulip/zulip master with `LINK_SETTINGS_TO_DATA` that might explain this behavior; it'll be in the 2.1.5 release.  See https://github.com/zulip/zulip/pull/14613.

**Comment by maltokyo** [comment]
great, thanks!  This will be easier than with ENV.
