### ISSUE TITLE
Install error on new machine (Debian Buster latest updates applied)

### ISSUE THREAD

**Issue by maltokyo** [zulip/docker-zulip#226]
I ran the install on a brand new VPS with Debian Buster.  Log is as below, and it did not work.

```
......... all install until here went well......
++ /root/zulip/scripts/lib/zulip_tools.py make_deploy_path
+ deploy_path=/home/zulip/deployments/2019-12-10-12-58-10
+ mv /root/zulip /home/zulip/deployments/2019-12-10-12-58-10
+ ln -nsf /home/zulip/deployments/next /root/zulip
+ ln -nsf /home/zulip/deployments/2019-12-10-12-58-10 /home/zulip/deployments/next
+ ln -nsf /home/zulip/deployments/2019-12-10-12-58-10 /home/zulip/deployments/current
+ ln -nsf /etc/zulip/settings.py /home/zulip/deployments/2019-12-10-12-58-10/zproject/prod_settings.py
+ mkdir -p /home/zulip/deployments/2019-12-10-12-58-10/prod-static/serve
+ cp -rT /home/zulip/deployments/2019-12-10-12-58-10/prod-static/serve /home/zulip/prod-static
+ chown -R zulip:zulip /home/zulip /var/log/zulip /etc/zulip/settings.py
+ '[' -e /home/zulip/prod-static/generated ']'
+ '[' -e /var/run/supervisor.sock ']'
+ '[' -n 1 ']'
+ set +x

 Success!

 Stopping because --no-init-db was passed.  To complete the installation, run:

   su zulip -c '/home/zulip/deployments/current/scripts/setup/initialize-database'
Removing intermediate container b7ac5d7bed90
 ---> 4ba1d46b7cbd
Step 22/27 : COPY entrypoint.sh /sbin/entrypoint.sh
 ---> 0528319e0835
Step 23/27 : COPY certbot-deploy-hook /sbin/certbot-deploy-hook
 ---> 98a59d40e62f
Step 24/27 : VOLUME ["$DATA_DIR"]
 ---> Running in 0784b5e8ac23
Removing intermediate container 0784b5e8ac23
 ---> 66b8a2a4f329
Step 25/27 : EXPOSE 80 443
 ---> Running in ca26af60b7ef
Removing intermediate container ca26af60b7ef
 ---> 8c89e1b479dd
Step 26/27 : ENTRYPOINT ["/sbin/entrypoint.sh"]
 ---> Running in 8c1a4c9e8930
Removing intermediate container 8c1a4c9e8930
 ---> 860d4e4820c7
Step 27/27 : CMD ["app:run"]
 ---> Running in 947881f9e43d
Removing intermediate container 947881f9e43d
 ---> 87a0aea1f129
Successfully built 87a0aea1f129
Successfully tagged zulip/docker-zulip:2.0.7-0
WARNING: Image for service zulip was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating docker-zulip_database_1 ... 
Creating docker-zulip_zulip_1    ... 
Creating docker-zulip_database_1  ... done
Creating docker-zulip_rabbitmq_1 ... 
Creating docker-zulip_redis_1     ... done
Creating docker-zulip_rabbitmq_1  ... done
Creating docker-zulip_memcached_1 ... done

ERROR: for zulip  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/9b0ccc461b0baa2076d5231f1f191f5cc882b1b5ca431bf06fbf36302d3bb469/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint docker-zulip_zulip_1 (b59b4542013343200464f27bdc99016758602113d8e8fd7d90d99da619f528b8): Bind for 0.0.0.0:443 failed: port is already allocated'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1107, in up
  File "compose/cli/main.py", line 1103, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 546, in execute_convergence_plan
  File "compose/service.py", line 467, in _execute_convergence_create
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 465, in <lambda>
  File "compose/service.py", line 457, in create_and_start
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[11565] Failed to execute script docker-compose
```

**Comment by timabbott** [comment]
It's clear from the traceback this is a networking issue with your Docker host.

**Comment by maltokyo** [comment]
Hi @timabbott could you please share a bit more advice here. I'm lost. This is a brand new commercial vps with a fresh install. Would you have some suggestion I can try? Other commands and dockers have no issues like this.

**Comment by timabbott** [comment]
I'd send this traceback to your cloud provider.  This line in praticular show that some piece of the Docker infrastructure is failing.

requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/9b0ccc461b0baa2076d5231f1f191f5cc882b1b5ca431bf06fbf36302d3bb469/start

**Comment by ghonche** [comment]
> Hi @timabbott could you please share a bit more advice here. I'm lost. This is a brand new commercial vps with a fresh install. Would you have some suggestion I can try? Other commands and dockers have no issues like this.

Hey, did you figure this out?
