### ISSUE TITLE
All docker-compose fail because talon blows up

### ISSUE THREAD

**Issue by 53c70r** [zulip/docker-zulip#231]
While trying to use docker-compose all builds fail in zulip build phase.
This happens within the zulip build environment:

```
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /srv/zulip-venv-cache/e1eb6592bce842070114364c4b6387c63e4c43d9/zulip-py3-venv/bin/python3
Also creating executable in /srv/zulip-venv-cache/e1eb6592bce842070114364c4b6387c63e4c43d9/zulip-py3-venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Collecting pip==19.0.1
  Downloading https://files.pythonhosted.org/packages/46/dc/7fd5df840efb3e56c8b4f768793a237ec4ee59891959d6a215d63f727023/pip-19.0.1-py2.py3-none-any.whl (1.4MB)
Collecting setuptools==40.7.1
  Downloading https://files.pythonhosted.org/packages/bf/ae/a23db1762646069742cc21393833577d3fa438eecaa59d11fb04fa57fcd5/setuptools-40.7.1-py2.py3-none-any.whl (574kB)
Collecting wheel==0.32.3
  Downloading https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
  Found existing installation: setuptools 45.0.0
    Uninstalling setuptools-45.0.0:
      Successfully uninstalled setuptools-45.0.0
  Found existing installation: wheel 0.33.6
    Uninstalling wheel-0.33.6:
      Successfully uninstalled wheel-0.33.6
Successfully installed pip-19.0.1 setuptools-40.7.1 wheel-0.32.3
Collecting django-bitfield==1.9.3+dev.0d2b15cdb5af5ddec88d41cac19c0f2ce1b1ad38 from git+https://github.com/zulip/django-bitfield@0d2b15cdb5af5ddec88d41cac19c0f2ce1b1ad38#egg=django-bitfield==1.9.3+dev.0d2b15cdb5af5ddec88d41cac19c0f2ce1b1ad38 (from -r /root/zulip/requirements/prod.txt (line 12))
  Cloning https://github.com/zulip/django-bitfield (to revision 0d2b15cdb5af5ddec88d41cac19c0f2ce1b1ad38) to /tmp/pip-install-i7mb3jiz/django-bitfield
  Requested django-bitfield==1.9.3+dev.0d2b15cdb5af5ddec88d41cac19c0f2ce1b1ad38 from git+https://github.com/zulip/django-bitfield@0d2b15cdb5af5ddec88d41cac19c0f2ce1b1ad38#egg=django-bitfield==1.9.3+dev.0d2b15cdb5af5ddec88d41cac19c0f2ce1b1ad38 (from -r /root/zulip/requirements/prod.txt (line 12)), but installing version 1.9.3
Collecting libthumbor==1.3.2zulip from git+https://github.com/zulip/libthumbor.git@60ed2431c07686a12f2770b2d852c5650f3ccfc6#egg=libthumbor==1.3.2zulip (from -r /root/zulip/requirements/prod.txt (line 13))
  Cloning https://github.com/zulip/libthumbor.git (to revision 60ed2431c07686a12f2770b2d852c5650f3ccfc6) to /tmp/pip-install-i7mb3jiz/libthumbor
  Requested libthumbor==1.3.2zulip from git+https://github.com/zulip/libthumbor.git@60ed2431c07686a12f2770b2d852c5650f3ccfc6#egg=libthumbor==1.3.2zulip (from -r /root/zulip/requirements/prod.txt (line 13)), but installing version 1.3.2
Collecting talon==1.2.10.zulip1 from git+https://github.com/zulip/talon.git@7d8bdc4dbcfcc5a73298747293b99fe53da55315#egg=talon==1.2.10.zulip1 (from -r /root/zulip/requirements/prod.txt (line 14))
  Cloning https://github.com/zulip/talon.git (to revision 7d8bdc4dbcfcc5a73298747293b99fe53da55315) to /tmp/pip-install-i7mb3jiz/talon
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i7mb3jiz/talon/setup.py", line 9, in <module>
        long_description=open("README.rst").read(),
      File "/srv/zulip-venv-cache/e1eb6592bce842070114364c4b6387c63e4c43d9/zulip-py3-venv/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 475: ordinal not in range(128)
```

**Comment by 53c70r** [comment]
e28099 which is "’" utf-8 gets parsed from README.rst which "zulip-py3-venv/lib/python3.6/encodings/ascii.py" can not handle?

**Comment by timabbott** [comment]
The issue here appears to be one of locales not being configured properly; this prevents Zulip from installing some of its locale-aware Python dependencies.  Since you're building your own container, have you patched the Dockerfile in any way?

**Comment by 53c70r** [comment]
I did not. The only thing i did was following the installation instructions under "Running a Zulip server with docker-compose".

**Comment by timabbott** [comment]
I would have expected using `docker-compose pull` to result in your using the standard built image, not building your own image.  Is it possible you skipped that step?

**Comment by 53c70r** [comment]
I used docker-compose pull.

**Comment by 53c70r** [comment]
More errors occur;
```
Using cached node modules from /srv/zulip-npm-cache/2ab4f6e476c38d2e16675f2df653984e27497690/node_modules
+ sudo -- tools/setup/install-shellcheck
2020-01-17 12:33:54 URL:https://storage.googleapis.com/shellcheck/shellcheck-v0.7.0.linux.x86_64.tar.xz [1545588/1545588] -> "shellcheck-v0.7.0.linux.x86_64.tar.xz" [1]
+ sudo -- rm -rf /srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv
+ sudo -- mkdir -p /srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv
+ sudo -- virtualenv -p python2.7 /srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv
New python executable in /srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv/bin/python2.7
Also creating executable in /srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /srv/zulip-venv-cach...r-venv/bin/python2.7 - setuptools pkg_resources pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 22, in <module>
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 65, in <module>
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 36, in vendored
  File "/srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/__init__.py", line 2, in <module>
  File "/srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/initialise.py", line 6, in <module>
  File "/srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/ansitowin32.py", line 7, in <module>
  File "/srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/winterm.py", line 2, in <module>
  File "/srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/win32.py", line 8, in <module>
  File "/usr/lib/python2.7/ctypes/__init__.py", line 556, in <module>
    _reset_cache()
  File "/usr/lib/python2.7/ctypes/__init__.py", line 276, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2375, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 992, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 922, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 817, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /srv/zulip-venv-cach...r-venv/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
Running virtualenv with interpreter /usr/bin/python2.7

Error running a subcommand of ./lib/provision.py: sudo -- virtualenv -p python2.7 /srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv
Actual error output for the subcommand is just above this.

Traceback (most recent call last):
  File "./lib/provision.py", line 410, in <module>
    main(options)
  File "./lib/provision.py", line 363, in main
    setup_venvs.main()
  File "/home/zulip/zulip/tools/setup/setup_venvs.py", line 20, in main
    patch_activate_script=True, virtualenv_args=['-p', 'python2.7'])
  File "/home/zulip/zulip/scripts/lib/setup_venv.py", line 290, in setup_virtualenv
    do_setup_virtualenv(cached_venv_path, requirements_file, virtualenv_args or [])
  File "/home/zulip/zulip/scripts/lib/setup_venv.py", line 318, in do_setup_virtualenv
    run_as_root(["virtualenv"] + virtualenv_args + [venv_path])
  File "/home/zulip/zulip/scripts/lib/zulip_tools.py", line 423, in run_as_root
    run(args, **kwargs)
  File "/home/zulip/zulip/scripts/lib/zulip_tools.py", line 200, in run
    subprocess.check_call(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '--', 'virtualenv', '-p', 'python2.7', '/srv/zulip-venv-cache/324f51b4322ec88cf8519cd16ce41e7967cd0f9f/zulip-thumbor-venv']' returned non-zero exit status 1.

Provisioning failed (exit code 1)!

* Look at the traceback(s) above to find more about the errors.
* Resolve the errors or get help on chat.
* If you can fix this yourself, you can re-run tools/provision at any time.
* Logs are here: zulip/var/log/provision.log

Error: error building at STEP "RUN ./tools/provision --production-travis": error while running runtime: exit status 1
125
```

**Comment by timabbott** [comment]
That error is a `MemoryError` -- almost certainly caused by having too little RAM allocated to your container.

**Comment by 53c70r** [comment]
Closing issue since the Problem was indeed a MemoryError.
thx.
