### ISSUE TITLE
Memcached Issues after 2.6.1 -> 3.0-0 Upgrade

### ISSUE THREAD

**Issue by H8to** [zulip/docker-zulip#265]
Hi there,

The server keeps sending the following issues when there is activity on the server.
I'm running the 3.0-0 release from Dockerhub, that you just published.
I started the server manually first, to see if the database migration happens, which did appear in the logs.

Should memcached have received an update too? The creation date for all other containers are older (7 weeks).
![image](https://user-images.githubusercontent.com/16744267/87850324-902f9d80-c8ef-11ea-8067-4bb1c0f4e4e7.png)

I use docker-compose. This issue might have to do with https://github.com/zulip/docker-zulip/issues/250 as the docker hostname might have changed during the upgrade. However, this seems to be fixed? I have not restarted the container any time between installation and now as it just worked like a charm up to now. :+1: 

Authentication error:
```
Logger django.pylibmc, from module django_pylibmc.memcached line 146:
Error generated by Anonymous user (not logged in) on deef374586b8 deployment

Traceback (most recent call last):
  File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/core/cache/backends/memcached.py", line 75, in get
    val = self._cache.get(key)
pylibmc.Error: error 41 from memcached_get(:1:ef2783a2e1787f30b2831fd3636cb): (0x2f687b0) AUTHENTICATION FAILURE,  host: memcached:11211 -> libmemcached/sasl.cc:292

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django_pylibmc/memcached.py", line 140, in set
    **COMPRESS_KWARGS)
pylibmc.ServerDown: error 47 from memcached_set: (0x2f687b0) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY,  host: memcached:11211 -> libmemcached/connect.cc:720


Deployed code:
- git: None
- ZULIP_VERSION: 3.0


Request info: none
``` 

Sever failed:
```
Logger django.pylibmc, from module django_pylibmc.memcached line 146:
Error generated by Anonymous user (not logged in) on deef374586b8 deployment

Traceback (most recent call last):
  File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/core/cache/backends/memcached.py", line 75, in get
    val = self._cache.get(key)
pylibmc.ServerDown: error 47 from memcached_get(:1:ef2783a2e1787f30b2831fd3636cb): (0x3fde550) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY, memcached:11211,  host: memcached:11211 -> libmemcached/connect.cc:811

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django_pylibmc/memcached.py", line 140, in set
    **COMPRESS_KWARGS)
pylibmc.ServerDown: error 47 from memcached_set: (0x3fde550) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY,  host: memcached:11211 -> libmemcached/connect.cc:720


Deployed code:
- git: None
- ZULIP_VERSION: 3.0


Request info: none
```

AttributeError: 'SessionStore' object has no attribute '_session_cache'
```
Logger django.pylibmc, from module django_pylibmc.memcached line 146:
Error generated by Anonymous user (not logged in) on deef374586b8 deployment

Traceback (most recent call last):
  File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/core/cache/backends/memcached.py", line 75, in get
    val = self._cache.get(key)
pylibmc.ServerDown: error 47 from memcached_get(:1:django.contrib.sessions.cache): (0x4419ac0) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY, memcached:11211,  host: memcached:11211 -> libmemcached/connect.cc:811

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django_pylibmc/memcached.py", line 140, in set
    **COMPRESS_KWARGS)
pylibmc.ServerDown: error 47 from memcached_set: (0x4419ac0) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY,  host: memcached:11211 -> libmemcached/connect.cc:720


Deployed code:
- git: None
- ZULIP_VERSION: 3.0


Request info: none
```

If you need any additional info just ask. I'm happy to help :)

**Comment by henrixapp** [comment]
I ran into the same issue. Updating the `docker-compose.yml` according to https://github.com/zulip/docker-zulip/issues/250#issuecomment-652600290 fixed the issue for me.

**Comment by H8to** [comment]
Thanks (Danke:1st_place_medal:) @henrixapp  
Adding `echo "zulip@localhost:$$MEMCACHED_PASSWORD" >> "$$MEMCACHED_SASL_PWDB"` to the `docker-compose.yml` did the trick for me.
