### ISSUE TITLE
Docker Zulip Upgrade from 2.1.7 to 3.0 Fails

### ISSUE THREAD

**Issue by maltokyo** [zulip/docker-zulip#266]
Upgrade (following in full instructions on the README) failed.  I am using the standard docker-compose.  Did upgrade work for anyone?

Here is the log:

```
# docker-compose up --remove-orphans
Creating zulipstippy_redis      ... done
Creating zulipstippy_postgresql ... done
Creating zulipstippy_memcached  ... done
Creating zulipstippy_zulip      ... done
Creating zulipstippy_rabbitmq   ... done
Attaching to zulipstippy_redis, zulipstippy_postgresql, zulipstippy_memcached, zulipstippy_zulip, zulipstippy_rabbitmq
zulipstippy_redis         | 1:C 27 Jul 2020 17:59:41.338 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
zulipstippy_redis         | 1:C 27 Jul 2020 17:59:41.338 # Redis version=6.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
zulipstippy_redis         | 1:C 27 Jul 2020 17:59:41.338 # Configuration loaded
zulipstippy_redis         | 1:M 27 Jul 2020 17:59:41.340 * Running mode=standalone, port=6379.
zulipstippy_redis         | 1:M 27 Jul 2020 17:59:41.340 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
zulipstippy_redis         | 1:M 27 Jul 2020 17:59:41.340 # Server initialized
zulipstippy_redis         | 1:M 27 Jul 2020 17:59:41.340 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
zulipstippy_redis         | 1:M 27 Jul 2020 17:59:41.340 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
zulipstippy_redis         | 1:M 27 Jul 2020 17:59:41.341 * Ready to accept connections
zulipstippy_zulip         | === Begin Initial Configuration Phase ===
zulipstippy_postgresql    | 
zulipstippy_postgresql    | PostgreSQL Database directory appears to contain a database; Skipping initialization
zulipstippy_postgresql    | 
zulipstippy_zulip         | Preparing and linking the uploads folder ...
zulipstippy_postgresql    | 2020-07-27 17:59:41.555 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
zulipstippy_postgresql    | 2020-07-27 17:59:41.555 UTC [1] LOG:  listening on IPv6 address "::", port 5432
zulipstippy_postgresql    | 2020-07-27 17:59:41.559 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
zulipstippy_postgresql    | 2020-07-27 17:59:41.585 UTC [20] LOG:  database system was shut down at 2020-07-27 17:48:55 UTC
zulipstippy_postgresql    | 2020-07-27 17:59:41.592 UTC [1] LOG:  database system is ready to accept connections
zulipstippy_zulip         | Prepared and linked the uploads directory.
zulipstippy_zulip         | Executing nginx configuration ...
zulipstippy_zulip         | Disabling https in nginx.
zulipstippy_zulip         | Notice: Compiled catalog for 3c51809e50e8 in environment production in 2.05 seconds
zulipstippy_zulip         | Notice: /Stage[main]/Zulip::Base/File[/etc/zulip/settings.py]/ensure: created
zulipstippy_zulip         | Notice: /Stage[main]/Zulip::Base/File[/etc/zulip/zulip-secrets.conf]/ensure: created
zulipstippy_zulip         | Notice: /Stage[main]/Zulip::Apt_repository/Exec[setup_apt_repo]/returns: executed successfully
zulipstippy_zulip         | Notice: /Stage[main]/Zulip::App_frontend/File[/etc/nginx/sites-available/zulip-enterprise]/content: content changed '{md5}062d03287b49273f099a14ea88cc3339' to '{md5}01b4c7a71e2fd7f0b5346630fa2f69fe'
zulipstippy_zulip         | Notice: /Stage[main]/Zulip::Nginx/Service[nginx]: Triggered 'refresh' from 1 event
zulipstippy_zulip         | Notice: Applied catalog in 1.58 seconds
zulipstippy_zulip         | Nginx configuration succeeded.
zulipstippy_zulip         | Certificates configuration succeeded.
zulipstippy_zulip         | Setting database configuration ...
zulipstippy_zulip         | Setting key "REMOTE_POSTGRES_HOST", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "REMOTE_POSTGRES_SSLMODE", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Database configuration succeeded.
zulipstippy_zulip         | Setting Zulip secrets ...
zulipstippy_zulip         | Generating Zulip secrets ...
zulipstippy_zulip         | generate_secrets: No new secrets to generate.
zulipstippy_zulip         | Secrets generation succeeded.
zulipstippy_zulip         | Zulip secrets configuration succeeded.
zulipstippy_zulip         | Activating authentication backends ...
zulipstippy_zulip         | Setting key "AUTHENTICATION_BACKENDS", type "array" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Adding authentication backend "EmailAuthBackend".
zulipstippy_zulip         | Authentication backend activation succeeded.
zulipstippy_zulip         | Executing Zulip configuration ...
zulipstippy_zulip         | Setting key "EMAIL_GATEWAY_IMAP_FOLDER", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "EMAIL_GATEWAY_IMAP_PORT", type "integer" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "EMAIL_GATEWAY_IMAP_SERVER", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "EMAIL_GATEWAY_LOGIN", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "EMAIL_GATEWAY_PATTERN", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "EMAIL_HOST", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "EMAIL_HOST_USER", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "EMAIL_PORT", type "integer" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "EMAIL_USE_SSL", type "bool" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "EMAIL_USE_TLS", type "bool" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "EXTERNAL_HOST", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "JITSI_SERVER_URL", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "MEMCACHED_LOCATION", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "PUSH_NOTIFICATION_BOUNCER_URL", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "RABBITMQ_HOST", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "RABBITMQ_USER", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "RATE_LIMITING", type "bool" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "REDIS_HOST", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "REDIS_PORT", type "integer" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "THUMBNAIL_IMAGES", type "bool" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "THUMBOR_URL", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Setting key "ZULIP_ADMINISTRATOR", type "string" in file "/etc/zulip/settings.py".
zulipstippy_zulip         | Zulip configuration succeeded.
zulipstippy_zulip         | Auto backup enabled.
zulipstippy_zulip         | === End Initial Configuration Phase ===
zulipstippy_zulip         | === Begin Bootstrap Phase ===
zulipstippy_zulip         | Waiting for database server to allow connections ...
zulipstippy_zulip         | Executing Zulip first start init ...
zulipstippy_zulip         | First Start Init not needed. Continuing.
zulipstippy_zulip         | Migrating Zulip to new version ...
zulipstippy_rabbitmq      | 2020-07-27 17:59:53.967 [info] <0.33.0> Application lager started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.324 [info] <0.33.0> Application mnesia started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.325 [info] <0.33.0> Application crypto started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.325 [info] <0.33.0> Application recon started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.325 [info] <0.33.0> Application jsx started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.325 [info] <0.33.0> Application os_mon started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.326 [info] <0.33.0> Application xmerl started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.326 [info] <0.33.0> Application inets started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.326 [info] <0.33.0> Application asn1 started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.327 [info] <0.33.0> Application public_key started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.327 [info] <0.33.0> Application ssl started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.328 [info] <0.33.0> Application ranch started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.328 [info] <0.33.0> Application ranch_proxy_protocol started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.328 [info] <0.33.0> Application rabbit_common started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 
zulipstippy_rabbitmq      |   ##  ##
zulipstippy_rabbitmq      |   ##  ##      RabbitMQ 3.7.7. Copyright (C) 2007-2018 Pivotal Software, Inc.
zulipstippy_rabbitmq      |   ##########  Licensed under the MPL.  See http://www.rabbitmq.com/
zulipstippy_rabbitmq      |   ######  ##
zulipstippy_rabbitmq      |   ##########  Logs: <stdout>
zulipstippy_rabbitmq      | 
zulipstippy_rabbitmq      |               Starting broker...
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.329 [info] <0.221.0> 
zulipstippy_rabbitmq      |  Starting RabbitMQ 3.7.7 on Erlang 20.3.8.5
zulipstippy_rabbitmq      |  Copyright (C) 2007-2018 Pivotal Software, Inc.
zulipstippy_rabbitmq      |  Licensed under the MPL.  See http://www.rabbitmq.com/
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.333 [info] <0.221.0> 
zulipstippy_rabbitmq      |  node           : rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      |  home dir       : /var/lib/rabbitmq
zulipstippy_rabbitmq      |  config file(s) : /etc/rabbitmq/rabbitmq.conf
zulipstippy_rabbitmq      |  cookie hash    : m0zQf4maYymtpr6GVfUuDQ==
zulipstippy_rabbitmq      |  log(s)         : <stdout>
zulipstippy_rabbitmq      |  database dir   : /var/lib/rabbitmq/mnesia/rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.364 [info] <0.250.0> Memory high watermark set to 12868 MiB (13493234892 bytes) of 32170 MiB (33733087232 bytes) total
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.383 [info] <0.265.0> Enabling free disk space monitoring
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.383 [info] <0.265.0> Disk free limit set to 50MB
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.388 [info] <0.267.0> Limiting to approx 1048476 file handles (943626 sockets)
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.389 [info] <0.268.0> FHC read buffering:  OFF
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.389 [info] <0.268.0> FHC write buffering: ON
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.393 [info] <0.221.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.420 [info] <0.221.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.420 [info] <0.221.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.421 [info] <0.221.0> Priority queues enabled, real BQ is rabbit_variable_queue
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.440 [info] <0.290.0> Starting rabbit_node_monitor
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.485 [info] <0.318.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@zulipstippy_rabbitmq/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.490 [info] <0.318.0> Starting message stores for vhost '/'
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.490 [info] <0.322.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.494 [info] <0.318.0> Started message store of type transient for vhost '/'
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.494 [info] <0.325.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.499 [info] <0.318.0> Started message store of type persistent for vhost '/'
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.718 [info] <0.465.0> started TCP Listener on [::]:5672
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.721 [info] <0.221.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.721 [info] <0.221.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:58.722 [info] <0.33.0> Application rabbit started on node rabbit@zulipstippy_rabbitmq
zulipstippy_rabbitmq      | 2020-07-27 17:59:59.369 [info] <0.5.0> Server startup complete; 0 plugins started.
zulipstippy_rabbitmq      |  completed with 0 plugins.
zulipstippy_postgresql    | 2020-07-27 18:00:01.191 UTC [28] ERROR:  could not create unique index "unique_user_count_null_subgroup"
zulipstippy_postgresql    | 2020-07-27 18:00:01.191 UTC [28] DETAIL:  Key (user_id, property, end_time)=(9, 15day_actives::day, 2019-12-07 00:00:00+00) is duplicated.
zulipstippy_postgresql    | 2020-07-27 18:00:01.191 UTC [28] STATEMENT:  CREATE UNIQUE INDEX "unique_user_count_null_subgroup" ON "analytics_usercount" ("user_id", "property", "end_time") WHERE "subgroup" IS NULL
zulipstippy_zulip         | Operations to perform:
zulipstippy_zulip         |   Apply all migrations: analytics, auth, confirmation, contenttypes, otp_static, otp_totp, sessions, social_django, two_factor, zerver
zulipstippy_zulip         | Running migrations:
zulipstippy_zulip         |   Applying analytics.0014_remove_fillstate_last_modified... OK
zulipstippy_zulip         |   Applying analytics.0015_clear_duplicate_counts... OK
zulipstippy_zulip         |   Applying analytics.0016_unique_constraint_when_subgroup_null...Traceback (most recent call last):
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
zulipstippy_zulip         |     return self.cursor.execute(sql, params)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zerver/lib/db.py", line 33, in execute
zulipstippy_zulip         |     return wrapper_execute(self, super().execute, query, vars)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zerver/lib/db.py", line 20, in wrapper_execute
zulipstippy_zulip         |     return action(sql, params)
zulipstippy_zulip         | psycopg2.errors.UniqueViolation: could not create unique index "unique_user_count_null_subgroup"
zulipstippy_zulip         | DETAIL:  Key (user_id, property, end_time)=(9, 15day_actives::day, 2019-12-07 00:00:00+00) is duplicated.
zulipstippy_zulip         | 
zulipstippy_zulip         | 
zulipstippy_zulip         | The above exception was the direct cause of the following exception:
zulipstippy_zulip         | 
zulipstippy_zulip         | Traceback (most recent call last):
zulipstippy_zulip         |   File "/home/zulip/deployments/current/manage.py", line 50, in <module>
zulipstippy_zulip         |     execute_from_command_line(sys.argv)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
zulipstippy_zulip         |     utility.execute()
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
zulipstippy_zulip         |     self.fetch_command(subcommand).run_from_argv(self.argv)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
zulipstippy_zulip         |     self.execute(*args, **cmd_options)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
zulipstippy_zulip         |     output = self.handle(*args, **options)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
zulipstippy_zulip         |     res = handle_func(*args, **kwargs)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
zulipstippy_zulip         |     fake_initial=fake_initial,
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
zulipstippy_zulip         |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
zulipstippy_zulip         |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
zulipstippy_zulip         |     state = migration.apply(state, schema_editor)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
zulipstippy_zulip         |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 827, in database_forwards
zulipstippy_zulip         |     schema_editor.add_constraint(model, self.constraint)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 345, in add_constraint
zulipstippy_zulip         |     self.execute(sql)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
zulipstippy_zulip         |     cursor.execute(sql, params)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
zulipstippy_zulip         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
zulipstippy_zulip         |     return executor(sql, params, many, context)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
zulipstippy_zulip         |     return self.cursor.execute(sql, params)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
zulipstippy_zulip         |     raise dj_exc_value.with_traceback(traceback) from exc_value
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
zulipstippy_zulip         |     return self.cursor.execute(sql, params)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zerver/lib/db.py", line 33, in execute
zulipstippy_zulip         |     return wrapper_execute(self, super().execute, query, vars)
zulipstippy_zulip         |   File "/home/zulip/deployments/2020-07-17-22-37-44/zerver/lib/db.py", line 20, in wrapper_execute
zulipstippy_zulip         |     return action(sql, params)
zulipstippy_zulip         | django.db.utils.IntegrityError: could not create unique index "unique_user_count_null_subgroup"
zulipstippy_zulip         | DETAIL:  Key (user_id, property, end_time)=(9, 15day_actives::day, 2019-12-07 00:00:00+00) is duplicated.
zulipstippy_zulip         | 
zulipstippy_zulip         | Zulip migration failed with exit code 1. Exiting.
zulipstippy_zulip exited with code 1
```

**Comment by timabbott** [comment]
This upgrade looks to have nothing to do with Docker -- it's a migration adding a unique index that should have always been present failing (presumably because in your database, some race had caused a violation of that index to already exist)

**Comment by timabbott** [comment]
The previous `analytics/migrations/0015_clear_duplicate_count.py` should have deleted the duplicate here.  I haven't seen any similar failures of that migration to clean up databases, so we'll need to debug here (or in chat.zulip.org).

Can you try running in a `manage.py shell` this and seeing whether it finds that duplicated row?  
```
realm_counts = RealmCount.objects.filter(subgroup=None).values(
    'realm_id', 'property', 'end_time').annotate(
        Count('id'), Sum('value')).filter(id__count__gt=1)
```

**Comment by maltokyo** [comment]
Hi @timabbott 
Thank you for your help


Now when I roll back to the old image and do a docker-compose up I get "realm does not exist" just below the login, after a correct user and password are entered.
![image](https://user-images.githubusercontent.com/1388507/88581016-d651d300-d04c-11ea-9a14-fcdb58f9556e.png)


I could however go to a manage.py shell, but when I run the command (in multiple lines or all in one line) I get no output at all.  Here is the result.  Please advise.

![image](https://user-images.githubusercontent.com/1388507/88580856-925ece00-d04c-11ea-9543-8ebc1daaf040.png)

**Comment by maltokyo** [comment]
And list_realms gives me nothing ;(

Ooops...  this is a real bind.  I do have a complete backup of the docker volume directory from before the upgrade, but unfortunately, it also gives me the same error upon restoration.  Not sure what to do now.

![image](https://user-images.githubusercontent.com/1388507/88581288-39dc0080-d04d-11ea-9219-237b0c6cc73a.png)

**Comment by maltokyo** [comment]
I am VERY sorry to use your time.  One moment please, it looks like user error.  Will report back and close this if it was.

**Comment by maltokyo** [comment]
Hi @timabbott 
Yes, I have confirmed again, after reverting to 2.1.7 successfully (I had a full backup of the volume too), I cannot get that command to output anything at all - I tried in one line and multi line:

![image](https://user-images.githubusercontent.com/1388507/88584794-81b15680-d052-11ea-8599-5a42c72d5837.png)

For now, I am back up and online on version 2.1.7 - any help to get rid of that db error so that I can upgrade would be great.  2.1.7 is working fine.  3.0 fails every time when I try to start the container after changing the docker-compose file to the new version to pull the 3.0 image.

Thank you!

**Comment by timabbott** [comment]
Can you run `print(realm_counts)`  after those steps?  Sorry I neglected that step which is needed to get useful output.  But I mainly want that output from the partially upgraded 3.0 version; not sure if you still have that.  

Backing up a bit:
* To upgrade to 3.0, you can likely just make a small fork that deletes `analytics/migrations/0016_unique_constraint_when_subgroup_null.py`, upgrade to that, and then we can proceed to debug the unique constraint issue as we would have on 2.1.7 but with you already upgraded.  No other changes depend on that migration.

And then for the debugging, what you'll want to do is run the commands in `analytics/migrations/0015_clear_duplicate_counts.py` manually, ideally after we've already moved to 3.0 (with that patch).

@arpit551 would you be up for helping @maltokyo figure out why migration 0015 doesn't clean up their database properly?  I think we should be able to just run the code from that migration manually in a management shell step by step to try to find the problematic objects.  We might be able to use `./manage.py clear_single_stat.py` instead as well.

**Comment by maltokyo** [comment]
Hi @timabbott 

Its not possible to login to the partially upgraded version as the container just stops on the error and hence you cannot login to it's cli using docker exec. So running that command there won't be feasible. 

I guess the best way would be to fix the db in 2.1.7 using steps you mentioned.

I'll give that a try. Most likely it will be on the weekend so as not to disturb users. 

I will revert back.

**Comment by timabbott** [comment]
OK, makes sense.  I think the "Skip migration and upgrade to 3.x" should work as an option too.

**Comment by arpit551** [comment]
@timabbott The duplicate was in UserCount Table
`
 django.db.utils.IntegrityError: could not create unique index "unique_user_count_null_subgroup"
 DETAIL:  Key (user_id, property, end_time)=(9, 15day_actives::day, 2019-12-07 00:00:00+00) is duplicated.
`
. migration 0015 would have deleted any duplicate in Realm Count. Now I think we should have taken care for other counts tables too. 

I think our code logic(database queries) should have avoided any duplicates before we introduced `0016_unique_constraint_when_subgroup_null` but `do_increment_logging_stat` function called from actions.py could have resulted in the duplicates we found during czo migration here [https://github.com/zulip/zulip/pull/13951#issuecomment-592399958](https://github.com/zulip/zulip/pull/13951#issuecomment-592399958). 
But in this case, the duplicate is in `15day_actives::day` which is not a LoggingCountStat.

**Comment by timabbott** [comment]
OK, makes sense; I would expect UserCount duplicates to be more rare but apparently still possible.  I think it would be reasonable to upgrade migrate 0015 in a commit we intend to backport to the 3.1 series to remove duplicates in StreamCount and UserCount as well to address this for @maltokyo and others in their situation.

**Comment by maltokyo** [comment]
Hi @timabbott 
Thank you. In this case I'll wait for 3.1? Or would you prefer I test something on 2.17?

**Comment by timabbott** [comment]
@maltokyo you should be able to just upgrade to 3.1, which was just released (should have the docker image in an hour or so).

**Comment by maltokyo** [comment]
Great. Thank you all. Will try again!
