### ISSUE TITLE
Provisioning failed (exit code 1)!

### ISSUE THREAD

**Issue by arthurpankiewicz** [zulip/docker-zulip#269]
When running `docker-compose up` on a fresh clone of the repo, Step 14 (`Step 14/27 : RUN ./tools/provision --build-release-tarball-only`) crashes the docker process. I'm not too sure where to begin debugging the issue, any advice is appreciated.

```
Error running a subcommand of ./lib/provision.py: sudo -- env DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends build-essential ca-certificates crudini curl default-jre-headless fonts-freefont-ttf gconf-service gettext gifsicle git hunspell-en-us jq libappindicator1 libatk-bridge2.0-0 libcurl4-openssl-dev libffi-dev libfontconfig1 libfreetype6-dev libgbm1 libgconf-2-4 libgtk-3-0 libjpeg-dev libldap2-dev libmagic1 libmemcached-dev libpng-dev libpq-dev libssl-dev libx11-xcb1 libxcb-dri3-0 libxml2-dev libxmlsec1-dev libxslt1-dev libxss1 memcached moreutils netcat pkg-config postgresql-10 postgresql-10-pgroonga puppet puppet-lint python3-dev python3-pip rabbitmq-server redis-server supervisor transifex-client unzip virtualenv wget xdg-utils zlib1g-dev
Actual error output for the subcommand is just above this.

Traceback (most recent call last):
  File "./lib/provision.py", line 354, in main
    install_system_deps()
  File "./lib/provision.py", line 234, in install_system_deps
    install_apt_deps(deps_to_install)
  File "./lib/provision.py", line 257, in install_apt_deps
    + deps_to_install,
  File "/home/zulip/zulip/scripts/lib/zulip_tools.py", line 464, in run_as_root
    run(args, **kwargs)
  File "/home/zulip/zulip/scripts/lib/zulip_tools.py", line 198, in run
    subprocess.check_call(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '--', 'env', 'DEBIAN_FRONTEND=noninteractive', 'apt-get', '-y', 'install', '--no-install-recommends', 'build-essential', 'ca-certificates', 'crudini', 'curl', 'default-jre-headless', 'fonts-freefont-ttf', 'gconf-service', 'gettext', 'gifsicle', 'git', 'hunspell-en-us', 'jq', 'libappindicator1', 'libatk-bridge2.0-0', 'libcurl4-openssl-dev', 'libffi-dev', 'libfontconfig1', 'libfreetype6-dev', 'libgbm1', 'libgconf-2-4', 'libgtk-3-0', 'libjpeg-dev', 'libldap2-dev', 'libmagic1', 'libmemcached-dev', 'libpng-dev', 'libpq-dev', 'libssl-dev', 'libx11-xcb1', 'libxcb-dri3-0', 'libxml2-dev', 'libxmlsec1-dev', 'libxslt1-dev', 'libxss1', 'memcached', 'moreutils', 'netcat', 'pkg-config', 'postgresql-10', 'postgresql-10-pgroonga', 'puppet', 'puppet-lint', 'python3-dev', 'python3-pip', 'rabbitmq-server', 'redis-server', 'supervisor', 'transifex-client', 'unzip', 'virtualenv', 'wget', 'xdg-utils', 'zlib1g-dev']' returned non-zero exit status 100.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lib/provision.py", line 450, in <module>
    main(options)
  File "./lib/provision.py", line 358, in main
    install_system_deps()
  File "./lib/provision.py", line 234, in install_system_deps
    install_apt_deps(deps_to_install)
  File "./lib/provision.py", line 257, in install_apt_deps
    + deps_to_install,
  File "/home/zulip/zulip/scripts/lib/zulip_tools.py", line 464, in run_as_root
    run(args, **kwargs)
  File "/home/zulip/zulip/scripts/lib/zulip_tools.py", line 198, in run
    subprocess.check_call(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '--', 'env', 'DEBIAN_FRONTEND=noninteractive', 'apt-get', '-y', 'install', '--no-install-recommends', 'build-essential', 'ca-certificates', 'crudini', 'curl', 'default-jre-headless', 'fonts-freefont-ttf', 'gconf-service', 'gettext', 'gifsicle', 'git', 'hunspell-en-us', 'jq', 'libappindicator1', 'libatk-bridge2.0-0', 'libcurl4-openssl-dev', 'libffi-dev', 'libfontconfig1', 'libfreetype6-dev', 'libgbm1', 'libgconf-2-4', 'libgtk-3-0', 'libjpeg-dev', 'libldap2-dev', 'libmagic1', 'libmemcached-dev', 'libpng-dev', 'libpq-dev', 'libssl-dev', 'libx11-xcb1', 'libxcb-dri3-0', 'libxml2-dev', 'libxmlsec1-dev', 'libxslt1-dev', 'libxss1', 'memcached', 'moreutils', 'netcat', 'pkg-config', 'postgresql-10', 'postgresql-10-pgroonga', 'puppet', 'puppet-lint', 'python3-dev', 'python3-pip', 'rabbitmq-server', 'redis-server', 'supervisor', 'transifex-client', 'unzip', 'virtualenv', 'wget', 'xdg-utils', 'zlib1g-dev']' returned non-zero exit status 100.

Provisioning failed (exit code 1)!

* Look at the traceback(s) above to find more about the errors.
* Resolve the errors or get help on chat.
* If you can fix this yourself, you can re-run tools/provision at any time.
* Logs are here: zulip/var/log/provision.log

ERROR: Service 'zulip' failed to build: The command '/bin/sh -c ./tools/provision --build-release-tarball-only' returned a non-zero code: 1
```

Thanks

**Comment by timabbott** [comment]
Did you see "Actual error output for the subcommand is just above this." near the top of the output?  We need the output above what you pasted to help debug.

But if I had to guess this is a networking error; `apt-get install` is failing.

**Comment by arthurpankiewicz** [comment]
I can't recall what the error further up was, after a few attempts it somehow managed to build so this is a bit of a defunct issue
