### ISSUE TITLE
"usr/share/postgresql/12/tsearch_data/en_us.dict": No such file or directory

### ISSUE THREAD

**Issue by stepanov-a** [zulip/docker-zulip#280]
Hello, i get latest version of your repository and trying to run.
I get an error 

[34mzulip_1      |[0m Empty var for key "EMAIL_HOST".
[34mzulip_1      |[0m Setting key "EMAIL_HOST_USER", type "string" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Setting key "EMAIL_PORT", type "integer" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Setting key "EMAIL_USE_SSL", type "bool" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Setting key "EMAIL_USE_TLS", type "bool" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Setting key "EXTERNAL_HOST", type "string" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Setting key "MEMCACHED_LOCATION", type "string" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Setting key "RABBITMQ_HOST", type "string" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Setting key "RABBITMQ_USER", type "string" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Setting key "RATE_LIMITING", type "bool" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Setting key "REDIS_HOST", type "string" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Setting key "REDIS_PORT", type "integer" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Setting key "ZULIP_ADMINISTRATOR", type "string" in file "/etc/zulip/settings.py".
[34mzulip_1      |[0m Zulip configuration succeeded.
[34mzulip_1      |[0m Auto backup enabled.
[34mzulip_1      |[0m === End Initial Configuration Phase ===
[34mzulip_1      |[0m === Begin Bootstrap Phase ===
[34mzulip_1      |[0m Waiting for database server to allow connections ...
[34mzulip_1      |[0m Executing Zulip first start init ...
[34mzulip_1      |[0m +++ readlink -f /home/zulip/deployments/current/scripts/setup/initialize-database
[34mzulip_1      |[0m ++ dirname /home/zulip/deployments/2020-11-17-13-07-09/scripts/setup/initialize-database
[34mzulip_1      |[0m + THIS_DIR=/home/zulip/deployments/2020-11-17-13-07-09/scripts/setup
[34mzulip_1      |[0m + cd /home/zulip/deployments/2020-11-17-13-07-09/scripts/setup/../..
[34mzulip_1      |[0m + ./manage.py checkconfig
[34mzulip_1      |[0m + ./manage.py migrate --noinput
[34mzulip_1      |[0m Operations to perform:
[34mzulip_1      |[0m   Apply all migrations: analytics, auth, confirmation, contenttypes, otp_static, otp_totp, sessions, social_django, two_factor, zerver
[34mzulip_1      |[0m Running migrations:
[34mzulip_1      |[0m   Applying zerver.0001_initial...Traceback (most recent call last):
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
[34mzulip_1      |[0m     return self.cursor.execute(sql)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zerver/lib/db.py", line 33, in execute
[34mzulip_1      |[0m     return wrapper_execute(self, super().execute, query, vars)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zerver/lib/db.py", line 20, in wrapper_execute
[34mzulip_1      |[0m     return action(sql, params)
[34mzulip_1      |[0m psycopg2.errors.ConfigFileError: could not open dictionary file "/usr/share/postgresql/12/tsearch_data/en_us.dict": No such file or directory
[34mzulip_1      |[0m 
[34mzulip_1      |[0m 
[34mzulip_1      |[0m The above exception was the direct cause of the following exception:
[34mzulip_1      |[0m 
[34mzulip_1      |[0m Traceback (most recent call last):
[34mzulip_1      |[0m   File "./manage.py", line 50, in <module>
[34mzulip_1      |[0m     execute_from_command_line(sys.argv)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in ex
ecute_from_command_line
[34mzulip_1      |[0m     utility.execute()
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in ex
ecute
[34mzulip_1      |[0m     self.fetch_command(subcommand).run_from_argv(self.argv)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_fr
om_argv
[34mzulip_1      |[0m     self.execute(*args, **cmd_options)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execut
e
[34mzulip_1      |[0m     output = self.handle(*args, **options)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
[34mzulip_1      |[0m     res = handle_func(*args, **kwargs)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 23
4, in handle
[34mzulip_1      |[0m     fake_initial=fake_initial,
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migr
ate
[34mzulip_1      |[0m     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _mig
rate_all_forwards
[34mzulip_1      |[0m     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in appl
y_migration
[34mzulip_1      |[0m     state = migration.apply(state, schema_editor)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in app
ly
[34mzulip_1      |[0m     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 10
5, in database_forwards
[34mzulip_1      |[0m     self._run_sql(schema_editor, self.sql)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 13
0, in _run_sql
[34mzulip_1      |[0m     schema_editor.execute(statement, params=None)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in exe
cute
[34mzulip_1      |[0m     cursor.execute(sql, params)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
[34mzulip_1      |[0m     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_w
ith_wrappers
[34mzulip_1      |[0m     return executor(sql, params, many, context)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
[34mzulip_1      |[0m     return self.cursor.execute(sql, params)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
[34mzulip_1      |[0m     raise dj_exc_value.with_traceback(traceback) from exc_value
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zulip-py3-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
[34mzulip_1      |[0m     return self.cursor.execute(sql)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zerver/lib/db.py", line 33, in execute
[34mzulip_1      |[0m     return wrapper_execute(self, super().execute, query, vars)
[34mzulip_1      |[0m   File "/home/zulip/deployments/2020-11-17-13-07-09/zerver/lib/db.py", line 20, in wrapper_execute
[34mzulip_1      |[0m     return action(sql, params)
**[34mzulip_1      |[0m django.db.utils.InternalError: could not open dictionary file "/usr/share/postgresql/12/tsearch_data/en_us.dict": No such file or directory
[34mzulip_1      |[0m 
[34mzulip_1      |[0m Zulip first start database initi failed in "initialize-database" exit code 1. Exiting.
[34mdocker-zulip-master_zulip_1 exited with code 1**

**Comment by stepanov-a** [comment]
https://github.com/zulip/docker-zulip/issues/92
