### ISSUE TITLE
Can't install 4.0, 4.2 or 4.3

### ISSUE THREAD

**Issue by riadabdel** [zulip/docker-zulip#309]
Hello,

I can't upgrade my stack from 3.3-0 to 4.* or make a fresh install of 4.*. I got thiss error:
Setting key "AUTH_LDAP_BIND_DN", type "string" in file "/etc/zulip/settings.py".
Setting key "AUTH_LDAP_REVERSE_EMAIL_SEARCH", type "array" in file "/etc/zulip/settings.py".
Setting key "AUTH_LDAP_SERVER_URI", type "string" in file "/etc/zulip/settings.py".
Setting key "AUTH_LDAP_USERNAME_ATTR", type "string" in file "/etc/zulip/settings.py".
Setting key "AUTH_LDAP_USER_ATTR_MAP", type "array" in file "/etc/zulip/settings.py".
Setting key "AUTH_LDAP_USER_SEARCH", type "array" in file "/etc/zulip/settings.py".
Setting key "EMAIL_HOST", type "string" in file "/etc/zulip/settings.py".
Setting key "EMAIL_PORT", type "integer" in file "/etc/zulip/settings.py".
Setting key "EXTERNAL_HOST", type "string" in file "/etc/zulip/settings.py".
Setting key "LDAP_APPEND_DOMAIN", type "array" in file "/etc/zulip/settings.py".
Setting key "LDAP_EMAIL_ATTR", type "string" in file "/etc/zulip/settings.py".
Setting key "MEMCACHED_LOCATION", type "string" in file "/etc/zulip/settings.py".
Setting key "RABBITMQ_HOST", type "string" in file "/etc/zulip/settings.py".
Setting key "RABBITMQ_USER", type "string" in file "/etc/zulip/settings.py".
Setting key "RATE_LIMITING", type "bool" in file "/etc/zulip/settings.py".
Setting key "REDIS_HOST", type "string" in file "/etc/zulip/settings.py".
Setting key "REDIS_PORT", type "integer" in file "/etc/zulip/settings.py".
Setting key "ZULIP_ADMINISTRATOR", type "string" in file "/etc/zulip/settings.py".
Traceback (most recent call last):
  File "/home/zulip/deployments/current/manage.py", line 52, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/zulip-venv-cache/9d0f5ac272f4e644b222ed65b0b5a996616a215f/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/srv/zulip-venv-cache/9d0f5ac272f4e644b222ed65b0b5a996616a215f/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/srv/zulip-venv-cache/9d0f5ac272f4e644b222ed65b0b5a996616a215f/zulip-py3-venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/zulip-venv-cache/9d0f5ac272f4e644b222ed65b0b5a996616a215f/zulip-py3-venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/srv/zulip-venv-cache/9d0f5ac272f4e644b222ed65b0b5a996616a215f/zulip-py3-venv/lib/python3.8/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'webpack_loader'
Error in the Zulip configuration. Exiting.

**Comment by timabbott** [comment]
I've never seen this error before.  Can you provide the fully output showing what command you were running when you saw this?  It's not obvious from the partial traceback what the actual issue is.

This may be easier to debug in "production help" on chat.zulip.org.

**Comment by riadabdel** [comment]
Hello,
I just resolved my problem, my bad, i didn't removed my volumes folders...
For information, when i go through the last update, rabbitmq crash: 06:33:17.609 [error] Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only
So i switch this option on my docker-compose file:
    volumes:
#      - 'rabbitmq:/var/lib/rabbitmq:rw'             > Old
      - 'rabbitmq:/var/lib/rabbitmq/mnesia'       > New
