### ISSUE TITLE
Error Email from Zulip - no idea what to do

### ISSUE THREAD

**Issue by maltokyo** [zulip/docker-zulip#317]
After upgrading to 4.4 and now 4.5 I get this email every few hours, not sure what it means.  Any advice is welcome.

```
Logger root, from module zerver.worker.queue_processors line 370:
Error generated by Anonymous user (not logged in) on cf1c90fe741b deployment

Traceback (most recent call last):
  File "/home/zulip/deployments/2021-07-25-23-24-50/zerver/worker/queue_processors.py", line 305, in do_consume
    consume_func(events)
  File "/home/zulip/deployments/2021-07-25-23-24-50/zerver/worker/queue_processors.py", line 345, in <lambda>
    consume_func = lambda events: self.consume(events[0])
  File "/home/zulip/deployments/2021-07-25-23-24-50/zerver/worker/queue_processors.py", line 682, in consume
    handle_push_notification(event["user_profile_id"], event)
  File "/home/zulip/deployments/2021-07-25-23-24-50/zerver/decorator.py", line 830, in wrapped_func
    ret = func(*args, **kwargs)
  File "/home/zulip/deployments/2021-07-25-23-24-50/zerver/lib/push_notifications.py", line 907, in handle_push_notification
    send_notifications_to_bouncer(user_profile_id, apns_payload, gcm_payload, gcm_options)
  File "/home/zulip/deployments/2021-07-25-23-24-50/zerver/lib/push_notifications.py", line 407, in send_notifications_to_bouncer
    send_json_to_push_bouncer("POST", "push/notify", post_data)
  File "/home/zulip/deployments/2021-07-25-23-24-50/zerver/lib/remote_server.py", line 104, in send_json_to_push_bouncer
    send_to_push_bouncer(
  File "/home/zulip/deployments/2021-07-25-23-24-50/zerver/lib/remote_server.py", line 57, in send_to_push_bouncer
    res = requests.request(
  File "/srv/zulip-venv-cache/cc77818846b328558cc9444c67cbbe0121ca80f4/zulip-py3-venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/zulip-venv-cache/cc77818846b328558cc9444c67cbbe0121ca80f4/zulip-py3-venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/zulip-venv-cache/cc77818846b328558cc9444c67cbbe0121ca80f4/zulip-py3-venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/srv/zulip-venv-cache/cc77818846b328558cc9444c67cbbe0121ca80f4/zulip-py3-venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/srv/zulip-venv-cache/cc77818846b328558cc9444c67cbbe0121ca80f4/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/srv/zulip-venv-cache/cc77818846b328558cc9444c67cbbe0121ca80f4/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/srv/zulip-venv-cache/cc77818846b328558cc9444c67cbbe0121ca80f4/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/srv/zulip-venv-cache/cc77818846b328558cc9444c67cbbe0121ca80f4/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/srv/zulip-venv-cache/cc77818846b328558cc9444c67cbbe0121ca80f4/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/srv/zulip-venv-cache/cc77818846b328558cc9444c67cbbe0121ca80f4/zulip-py3-venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
  File "/home/zulip/deployments/2021-07-25-23-24-50/zerver/worker/queue_processors.py", line 351, in timer_expired
    raise WorkerTimeoutException(limit, len(events))
zerver.worker.queue_processors.WorkerTimeoutException: Timed out after 30 seconds processing 1 events


Deployed code:
- git: None
- ZULIP_VERSION: 4.5


Request info: none
```

**Comment by timabbott** [comment]
@maltokyo I believe that error is caused by, well, a timeout when trying to send push notifications to the mobile push notifications service.  If I had to guess, you have a firewall that is causing requests to that service to hang indefinitely.
