### ISSUE TITLE
UserProfile matching query does not exist

### ISSUE THREAD

**Issue by jerrybb** [zulip/docker-zulip#335]
Hi, I am experiencing Internal server error message on different occasions. For example when user logins for first time.
![image](https://user-images.githubusercontent.com/44587704/147447320-1c55a6c9-2cae-4ce5-891f-0f6f8bb220d5.png)

After page refresh user Zulip loads successfully.

There is LDAP (Active Directory) integration configured.
mail attribute is used for email and username.

Special service user is used for LDAP binding - member of "domain users".

Any idea what could be issue?

Jernej

Logger zerver.middleware.json_error_handler, from module zerver.middleware line 450:
Error generated by User <user@example.com> (Member) on im.example.com deployment

Traceback (most recent call last):
 File "/srv/zulip-venv-cache/a7fb0fe17c8b91b591927bfa8f133a90b20f3d18/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/home/zulip/deployments/2021-12-26-06-07-17/./zerver/lib/rest.py", line 33, in _wrapped_view_func
   response = view_func(request, *args, **kwargs)
 File "/srv/zulip-venv-cache/a7fb0fe17c8b91b591927bfa8f133a90b20f3d18/zulip-py3-venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
   return view_func(*args, **kwargs)
 File "/home/zulip/deployments/2021-12-26-06-07-17/./zerver/lib/rest.py", line 166, in rest_dispatch
   return target_function(request, **kwargs)
 File "/srv/zulip-venv-cache/a7fb0fe17c8b91b591927bfa8f133a90b20f3d18/zulip-py3-venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
   response = view_func(request, *args, **kwargs)
 File "/home/zulip/deployments/2021-12-26-06-07-17/./zerver/decorator.py", line 751, in _wrapped_view_func
   return authenticate_log_and_execute_json(
 File "/home/zulip/deployments/2021-12-26-06-07-17/./zerver/decorator.py", line 738, in authenticate_log_and_execute_json
   return limited_view_func(request, user_profile, *args, **kwargs)
 File "/home/zulip/deployments/2021-12-26-06-07-17/./zerver/decorator.py", line 880, in wrapped_func
   return func(request, *args, **kwargs)
 File "/home/zulip/deployments/2021-12-26-06-07-17/./zerver/lib/request.py", line 390, in _wrapped_view_func
   return view_func(request, *args, **kwargs)
 File "/home/zulip/deployments/2021-12-26-06-07-17/./zerver/views/message_send.py", line 294, in send_message_backend
   ret = check_send_message(
 File "/home/zulip/deployments/2021-12-26-06-07-17/./zerver/lib/actions.py", line 2679, in check_send_message
   return do_send_messages([message])[0]
 File "/home/zulip/deployments/2021-12-26-06-07-17/./zerver/lib/actions.py", line 1991, in do_send_messages
   welcome_bot_id = get_system_bot(settings.WELCOME_BOT).id
 File "/home/zulip/deployments/2021-12-26-06-07-17/./zerver/lib/cache.py", line 204, in func_with_caching
   val = func(*args, **kwargs)
 File "/home/zulip/deployments/2021-12-26-06-07-17/./zerver/models.py", line 2910, in get_system_bot
   return UserProfile.objects.select_related().get(email__iexact=email.strip())
 File "/srv/zulip-venv-cache/a7fb0fe17c8b91b591927bfa8f133a90b20f3d18/zulip-py3-venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
   raise self.model.DoesNotExist(
zerver.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.

Deployed code:
- git: None
- ZULIP_VERSION: 4.8

Request info:
- path: /json/messages
- POST: {'type': ['private'], 'content': ['**********'], 'sender_id': ['7'], 'queue_id': ['1640587029:2'], 'stream': ['**********'], 'topic': [''], 'to': ['**********'], 'reply_to': ['myself@example.com'], 'private_message_recipient': ['myself@example.com'], 'to_user_ids': ['1'], 'local_id': ['4.01'], 'locally_echoed': ['true']}
- REMOTE_ADDR: "43.41.78.228"
- QUERY_STRING: ""
- SERVER_NAME: ""

**Comment by timabbott** [comment]
It's hard to tell from the report, but it looks like `initialize_database` failed (errors should have been in log files), and thus the system bots that the system expects to exist aren't present.

I'm pretty sure we fixed this case to have better error messages as couple years ago.
