### ISSUE TITLE
Multiple workers not working on zulip 4.8-1 docker

### ISSUE THREAD

**Issue by amolvishwakarma** [zulip/docker-zulip#341]
Hi @timabbott ,

I am facing a strange issue suddenly the workers stopped working attaching supervisorctl status screenshot:
![image](https://user-images.githubusercontent.com/57523705/152110633-6420a7b6-c488-4b66-80b8-a2ecbeb6e4ec.png)

Ideally it should show something like this:

```
When everything is running as expected, you will see something like this:

process-fts-updates                                             RUNNING   pid 11392, uptime 19:40:06
smokescreen                                                     RUNNING   pid 3113, uptime 29 days, 21:58:32
teleport_node                                                   RUNNING   pid 15683, uptime 3 days, 13:01:58
zulip-django                                                    RUNNING   pid 11441, uptime 19:39:57
zulip-tornado                                                   RUNNING   pid 11397, uptime 19:40:03
zulip_deliver_scheduled_emails                                  RUNNING   pid 10289, uptime 19:41:04
zulip_deliver_scheduled_messages                                RUNNING   pid 10294, uptime 19:41:02
zulip-workers:zulip_events_deferred_work                        RUNNING   pid 10314, uptime 19:41:00
zulip-workers:zulip_events_digest_emails                        RUNNING   pid 10339, uptime 19:40:57
zulip-workers:zulip_events_email_mirror                         RUNNING   pid 10751, uptime 19:40:52
zulip-workers:zulip_events_email_senders                        RUNNING   pid 10769, uptime 19:40:49
zulip-workers:zulip_events_embed_links                          RUNNING   pid 11035, uptime 19:40:46
zulip-workers:zulip_events_embedded_bots                        RUNNING   pid 11139, uptime 19:40:43
zulip-workers:zulip_events_error_reports                        RUNNING   pid 11154, uptime 19:40:40
zulip-workers:zulip_events_invites                              RUNNING   pid 11261, uptime 19:40:36
zulip-workers:zulip_events_missedmessage_emails                 RUNNING   pid 11346, uptime 19:40:21
zulip-workers:zulip_events_missedmessage_mobile_notifications   RUNNING   pid 11351, uptime 19:40:19
zulip-workers:zulip_events_outgoing_webhooks                    RUNNING   pid 11358, uptime 19:40:17
zulip-workers:zulip_events_user_activity                        RUNNING   pid 11365, uptime 19:40:14
zulip-workers:zulip_events_user_activity_interval               RUNNING   pid 11376, uptime 19:40:11
zulip-workers:zulip_events_user_presence                        RUNNING   pid 11384, uptime 19:40:08
```

On January 26, Let’s Encrypt announced that all certificates verified through a TLS-ALPN-01 challenge and created between October 29, 2021, and 00:48 UTC January 26, 2022, will be revoked starting at 16:00 UTC on January 28, 2022. So I regenerated the certificate on monday 31 Jan .

Application is working fine but user presence status is not visible. None of the users showing online.

command: tail -100 /var/log/zulip/workers.log
```
workers.log 

2022-02-02 00:02:44.680 INFO [] Processing traceback with type server for None
2022-02-02 00:07:12.258 INFO [] Processing traceback with type server for None
2022-02-02 00:15:13.816 INFO [] Processing traceback with type server for None
2022-02-02 00:17:13.187 INFO [] Processing traceback with type server for None
2022-02-02 00:18:03.111 INFO [] Processing traceback with type server for None
2022-02-02 00:25:36.631 INFO [] Processing traceback with type server for None
2022-02-02 00:27:13.783 INFO [] Processing traceback with type server for None
2022-02-02 00:37:14.099 INFO [] Processing traceback with type server for None
2022-02-02 00:47:13.753 INFO [] Processing traceback with type server for None
2022-02-02 00:51:34.919 INFO [] Processing traceback with type server for None
2022-02-02 00:57:14.234 INFO [] Processing traceback with type server for None
2022-02-02 01:02:11.322 INFO [] Processing traceback with type server for None
2022-02-02 01:07:13.535 INFO [] Processing traceback with type server for None
2022-02-02 01:08:02.544 INFO [] Processing traceback with type server for None
2022-02-02 01:16:14.174 INFO [] Processing traceback with type server for None
2022-02-02 01:17:13.557 INFO [] Processing traceback with type server for None
2022-02-02 01:23:26.417 INFO [] Processing traceback with type server for None
2022-02-02 01:27:14.286 INFO [] Processing traceback with type server for None
2022-02-02 01:29:44.564 INFO [] Processing traceback with type server for None
2022-02-02 01:37:14.283 INFO [] Processing traceback with type server for None
2022-02-02 01:41:10.181 INFO [] Processing traceback with type server for None
2022-02-02 01:47:13.476 INFO [] Processing traceback with type server for None
2022-02-02 01:55:19.374 INFO [] Processing traceback with type server for None
2022-02-02 01:57:14.273 INFO [] Processing traceback with type server for None
2022-02-02 02:00:02.280 INFO [] Processing traceback with type server for None
2022-02-02 02:02:20.609 INFO [process_queue] launching queue worker thread deferred_work
2022-02-02 02:02:20.706 INFO [process_queue] launching queue worker thread digest_emails
2022-02-02 02:02:20.718 INFO [process_queue] launching queue worker thread email_mirror
2022-02-02 02:02:20.728 INFO [process_queue] launching queue worker thread embed_links
2022-02-02 02:02:20.773 INFO [process_queue] launching queue worker thread embedded_bots
2022-02-02 02:02:20.800 INFO [process_queue] launching queue worker thread error_reports
2022-02-02 02:02:20.830 INFO [process_queue] launching queue worker thread invites
2022-02-02 02:02:20.893 INFO [process_queue] launching queue worker thread email_senders
2022-02-02 02:02:26.636 INFO [] Processing traceback with type server for None
2022-02-02 02:02:38.374 INFO [] Processing traceback with type server for None
2022-02-02 02:12:26.671 INFO [] Processing traceback with type server for None
2022-02-02 02:13:26.463 INFO [] Processing traceback with type server for None
2022-02-02 02:22:25.526 INFO [] Processing traceback with type server for None
2022-02-02 02:24:50.419 INFO [] Processing traceback with type server for None
2022-02-02 02:32:26.123 INFO [] Processing traceback with type server for None
2022-02-02 02:36:48.053 INFO [] Processing traceback with type server for None
2022-02-02 02:41:47.535 INFO [] Processing traceback with type server for None
2022-02-02 02:42:26.379 INFO [] Processing traceback with type server for None
2022-02-02 02:46:49.754 INFO [] Processing traceback with type server for None
2022-02-02 02:52:26.392 INFO [] Processing traceback with type server for None
2022-02-02 03:00:02.971 INFO [] Processing traceback with type server for None
2022-02-02 03:01:01.300 INFO [] Processing traceback with type server for None
2022-02-02 03:02:26.959 INFO [] Processing traceback with type server for None
2022-02-02 03:11:30.272 INFO [] Processing traceback with type server for None
2022-02-02 03:12:27.257 INFO [] Processing traceback with type server for None
2022-02-02 03:22:28.154 INFO [] Processing traceback with type server for None
2022-02-02 03:27:50.901 INFO [] Processing traceback with type server for None
2022-02-02 03:28:38.442 INFO [] Processing traceback with type server for None
2022-02-02 03:32:28.003 INFO [] Processing traceback with type server for None
2022-02-02 03:38:11.691 INFO [] Processing traceback with type server for None
2022-02-02 03:42:27.859 INFO [] Processing traceback with type server for None
2022-02-02 03:49:54.827 INFO [] Processing traceback with type server for None
2022-02-02 03:52:28.231 INFO [] Processing traceback with type server for None
2022-02-02 03:59:45.292 INFO [] Processing traceback with type server for None
2022-02-02 04:01:19.265 INFO [] Processing traceback with type server for None
2022-02-02 04:02:27.548 INFO [] Processing traceback with type server for None
2022-02-02 04:12:28.428 INFO [] Processing traceback with type server for None
2022-02-02 04:13:14.615 INFO [] Processing traceback with type server for None
2022-02-02 04:22:27.796 INFO [] Processing traceback with type server for None
2022-02-02 04:24:30.448 INFO [] Processing traceback with type server for None
2022-02-02 04:32:28.764 INFO [] Processing traceback with type server for None
2022-02-02 04:35:16.945 INFO [] Processing traceback with type server for None
2022-02-02 04:42:28.270 INFO [] Processing traceback with type server for None
2022-02-02 04:47:54.763 INFO [] Processing traceback with type server for None
2022-02-02 04:52:28.463 INFO [] Processing traceback with type server for None
2022-02-02 04:52:49.743 INFO [] Processing traceback with type server for None
2022-02-02 05:02:27.897 INFO [] Processing traceback with type server for None
2022-02-02 05:03:28.207 INFO [] Processing traceback with type server for None
2022-02-02 05:11:03.231 INFO [] Processing traceback with type server for None
2022-02-02 05:12:28.264 INFO [] Processing traceback with type server for None
2022-02-02 05:14:18.709 INFO [] Processing traceback with type server for None
2022-02-02 05:22:28.510 INFO [] Processing traceback with type server for None
2022-02-02 05:29:22.813 INFO [] Processing traceback with type server for None
2022-02-02 05:32:28.332 INFO [] Processing traceback with type server for None
2022-02-02 05:35:03.436 INFO [] Processing traceback with type server for None
2022-02-02 05:42:28.228 INFO [] Processing traceback with type server for None
2022-02-02 05:47:29.704 INFO [] Processing traceback with type server for None
2022-02-02 05:52:27.628 INFO [] Processing traceback with type server for None
2022-02-02 06:00:14.197 INFO [] Processing traceback with type server for None
2022-02-02 06:00:25.038 INFO [] Processing traceback with type server for None
2022-02-02 06:02:28.188 INFO [] Processing traceback with type server for None
2022-02-02 06:11:07.285 INFO [] Processing traceback with type server for None
2022-02-02 06:12:28.800 INFO [] Processing traceback with type server for None
2022-02-02 06:22:27.971 INFO [] Processing traceback with type server for None
2022-02-02 06:24:03.739 INFO [] Processing traceback with type server for None
2022-02-02 06:32:29.062 INFO [] Processing traceback with type server for None
2022-02-02 06:35:04.773 INFO [] Processing traceback with type server for None
2022-02-02 06:38:38.566 INFO [] Processing traceback with type server for None
2022-02-02 06:42:27.733 INFO [] Processing traceback with type server for None
2022-02-02 06:49:39.944 INFO [] Processing traceback with type server for None
2022-02-02 06:52:28.818 INFO [] Processing traceback with type server for None
2022-02-02 06:59:47.640 INFO [] Processing traceback with type server for None
2022-02-02 07:02:28.370 INFO [] Processing traceback with type server for None
2022-02-02 07:12:02.795 INFO [] Processing traceback with type server for None
2022-02-02 07:12:28.175 INFO [] Processing traceback with type server for None
```

**Comment by amolvishwakarma** [comment]
Please let me know if any details were required @timabbott , this issue is strange not able to replicate also.

**Comment by timabbott** [comment]
What's in `/var/log/zulip/events.log` and/or `errors.log` ? I expect there to be exceptions there.

Your `supervisorctl status` output is normal for a server with <4GB of RAM; we run the `events` workers multithreaded rather than multi-process in that configuration.

In any case #production help in chat.zulip.org is the right place to debug further.

**Comment by amolvishwakarma** [comment]
Sorry for the delayed response @timabbott but I think it is due to the http host header issue in my configuration because using traefik as a proxy and only allowed the main domain and loopback localhost address.I will get back to you with the updates and the resolution once it is fixed.Thanks you so much for your help @timabbott

**Comment by amolvishwakarma** [comment]
Yes there are exceptions @timabbott please have a look 

```
var/log/zulip/events.log

root@68681f4fba88:/var/log/zulip# tail -200 events.log 
2022-02-27 01:00:53.230 INFO [] Processing traceback with type server for None
2022-02-27 01:00:55.027 INFO [] Processing traceback with type server for None
2022-02-27 01:00:55.828 INFO [] Processing traceback with type server for None
2022-02-27 01:00:56.728 INFO [] Processing traceback with type server for None
2022-02-27 01:00:57.617 INFO [] Processing traceback with type server for None
2022-02-27 01:00:58.428 INFO [] Processing traceback with type server for None
2022-02-27 01:00:59.332 INFO [] Processing traceback with type server for None
2022-02-27 01:01:00.242 INFO [] Processing traceback with type server for None
2022-02-27 01:01:01.148 INFO [] Processing traceback with type server for None
2022-02-27 01:01:02.066 INFO [] Processing traceback with type server for None
2022-02-27 01:01:02.972 INFO [] Processing traceback with type server for None
2022-02-27 01:01:03.786 INFO [] Processing traceback with type server for None
2022-02-27 01:01:04.679 INFO [] Processing traceback with type server for None
2022-02-27 01:01:05.577 INFO [] Processing traceback with type server for None
2022-02-27 01:01:06.386 INFO [] Processing traceback with type server for None
2022-02-27 01:01:07.286 INFO [] Processing traceback with type server for None
2022-02-27 01:01:08.173 INFO [] Processing traceback with type server for None
2022-02-27 01:01:08.983 INFO [] Processing traceback with type server for None
2022-02-27 01:01:09.883 INFO [] Processing traceback with type server for None
2022-02-27 01:01:10.693 INFO [] Processing traceback with type server for None
2022-02-27 01:01:11.599 INFO [] Processing traceback with type server for None
2022-02-27 01:01:12.399 INFO [] Processing traceback with type server for None
2022-02-27 01:01:13.215 INFO [] Processing traceback with type server for None
2022-02-27 01:01:14.002 INFO [] Processing traceback with type server for None
2022-02-27 01:01:15.802 INFO [] Processing traceback with type server for None
2022-02-27 01:01:16.691 INFO [] Processing traceback with type server for None
2022-02-27 01:01:18.477 INFO [] Processing traceback with type server for None
2022-02-27 01:01:19.399 INFO [] Processing traceback with type server for None
2022-02-27 01:01:20.248 INFO [] Processing traceback with type server for None
2022-02-27 01:01:21.052 INFO [] Processing traceback with type server for None
2022-02-27 01:01:21.852 INFO [] Processing traceback with type server for None
2022-02-27 01:01:22.664 INFO [] Processing traceback with type server for None
2022-02-27 01:01:23.479 INFO [] Processing traceback with type server for None
2022-02-27 01:01:24.294 INFO [] Processing traceback with type server for None
2022-02-27 01:01:25.095 INFO [] Processing traceback with type server for None
2022-02-27 01:01:25.919 INFO [] Processing traceback with type server for None
2022-02-27 01:01:26.817 INFO [] Processing traceback with type server for None
2022-02-27 01:01:27.720 INFO [] Processing traceback with type server for None
2022-02-27 01:01:28.534 INFO [] Processing traceback with type server for None
2022-02-27 01:01:29.670 INFO [] Processing traceback with type server for None
2022-02-27 01:01:30.487 INFO [] Processing traceback with type server for None
2022-02-27 01:01:31.293 INFO [] Processing traceback with type server for None
2022-02-27 01:01:32.094 INFO [] Processing traceback with type server for None
2022-02-27 01:01:33.015 INFO [] Processing traceback with type server for None
2022-02-27 01:01:33.830 INFO [] Processing traceback with type server for None
2022-02-27 01:01:34.621 INFO [] Processing traceback with type server for None
2022-02-27 01:01:35.521 INFO [] Processing traceback with type server for None
2022-02-27 01:01:36.562 INFO [] Processing traceback with type server for None
2022-02-27 01:01:37.363 INFO [] Processing traceback with type server for None
2022-02-27 01:01:38.173 INFO [] Processing traceback with type server for None
2022-02-27 01:01:38.986 INFO [] Processing traceback with type server for None
2022-02-27 01:01:39.882 INFO [] Processing traceback with type server for None
2022-02-27 01:01:40.682 INFO [] Processing traceback with type server for None
2022-02-27 01:01:41.570 INFO [] Processing traceback with type server for None
2022-02-27 01:01:42.483 INFO [] Processing traceback with type server for None
2022-02-27 01:01:43.273 INFO [] Processing traceback with type server for None
2022-02-27 01:01:44.082 INFO [] Processing traceback with type server for None
2022-02-27 01:01:44.885 INFO [] Processing traceback with type server for None
2022-02-27 01:01:45.687 INFO [] Processing traceback with type server for None
2022-02-27 01:01:46.496 INFO [] Processing traceback with type server for None
2022-02-27 01:01:47.297 INFO [] Processing traceback with type server for None
2022-02-27 01:01:48.119 INFO [] Processing traceback with type server for None
2022-02-27 01:01:48.933 INFO [] Processing traceback with type server for None
2022-02-27 01:01:49.823 INFO [] Processing traceback with type server for None
2022-02-27 01:01:50.634 INFO [] Processing traceback with type server for None
2022-02-27 01:01:51.434 INFO [] Processing traceback with type server for None
2022-02-27 01:01:52.224 INFO [] Processing traceback with type server for None
2022-02-27 01:01:53.021 INFO [] Processing traceback with type server for None
2022-02-27 01:01:53.822 INFO [] Processing traceback with type server for None
2022-02-27 01:01:54.636 INFO [] Processing traceback with type server for None
2022-02-27 01:01:55.451 INFO [] Processing traceback with type server for None
2022-02-27 01:01:56.251 INFO [] Processing traceback with type server for None
2022-02-27 01:01:57.044 INFO [] Processing traceback with type server for None
2022-02-27 01:01:57.839 INFO [] Processing traceback with type server for None
2022-02-27 01:01:58.649 INFO [] Processing traceback with type server for None
2022-02-27 01:01:59.450 INFO [] Processing traceback with type server for None
2022-02-27 01:02:00.258 INFO [] Processing traceback with type server for None
2022-02-27 01:02:01.071 INFO [] Processing traceback with type server for None
2022-02-27 01:02:01.917 INFO [] Processing traceback with type server for None
2022-02-27 01:02:02.761 INFO [] Processing traceback with type server for None
2022-02-27 01:02:03.657 INFO [] Processing traceback with type server for None
2022-02-27 01:02:04.497 INFO [] Processing traceback with type server for None
2022-02-27 01:02:05.297 INFO [] Processing traceback with type server for None
2022-02-27 01:02:06.103 INFO [] Processing traceback with type server for None
2022-02-27 01:02:06.903 INFO [] Processing traceback with type server for None
2022-02-27 01:02:07.711 INFO [] Processing traceback with type server for None
2022-02-27 01:02:08.520 INFO [] Processing traceback with type server for None
2022-02-27 01:02:09.325 INFO [] Processing traceback with type server for None
2022-02-27 01:02:10.129 INFO [] Processing traceback with type server for None
2022-02-27 01:02:10.940 INFO [] Processing traceback with type server for None
2022-02-27 01:02:11.738 INFO [] Processing traceback with type server for None
2022-02-27 01:02:12.532 INFO [] Processing traceback with type server for None
2022-02-27 01:02:13.335 INFO [] Processing traceback with type server for None
2022-02-27 01:02:14.135 INFO [] Processing traceback with type server for None
2022-02-27 01:02:14.938 INFO [] Processing traceback with type server for None
2022-02-27 01:02:15.731 INFO [] Processing traceback with type server for None
2022-02-27 01:02:16.547 INFO [] Processing traceback with type server for None
2022-02-27 01:02:17.350 INFO [] Processing traceback with type server for None
2022-02-27 01:02:18.156 INFO [] Processing traceback with type server for None
2022-02-27 01:02:18.960 INFO [] Processing traceback with type server for None
2022-02-27 01:02:19.760 INFO [] Processing traceback with type server for None
2022-02-27 01:02:20.574 INFO [] Processing traceback with type server for None
2022-02-27 01:02:21.361 INFO [] Processing traceback with type server for None
2022-02-27 01:02:22.170 INFO [] Processing traceback with type server for None
2022-02-27 01:02:22.982 INFO [] Processing traceback with type server for None
2022-02-27 01:02:23.771 INFO [] Processing traceback with type server for None
2022-02-27 01:02:24.579 INFO [] Processing traceback with type server for None
2022-02-27 01:02:25.377 INFO [] Processing traceback with type server for None
2022-02-27 01:02:26.168 INFO [] Processing traceback with type server for None
2022-02-27 01:02:26.969 INFO [] Processing traceback with type server for None
2022-02-27 01:02:27.781 INFO [] Processing traceback with type server for None
2022-02-27 01:02:28.583 INFO [] Processing traceback with type server for None
2022-02-27 01:02:29.398 INFO [] Processing traceback with type server for None
2022-02-27 01:02:30.198 INFO [] Processing traceback with type server for None
2022-02-27 01:02:31.010 INFO [] Processing traceback with type server for None
2022-02-27 01:02:31.797 INFO [] Processing traceback with type server for None
2022-02-27 01:02:32.605 INFO [] Processing traceback with type server for None
2022-02-27 01:02:33.420 INFO [] Processing traceback with type server for None
2022-02-27 01:02:34.209 INFO [] Processing traceback with type server for None
2022-02-27 01:02:35.014 INFO [] Processing traceback with type server for None
2022-02-27 01:02:35.815 INFO [] Processing traceback with type server for None
2022-02-27 01:02:37.101 INFO [] Processing traceback with type server for None
2022-02-27 01:02:37.887 INFO [] Processing traceback with type server for None
2022-02-27 01:02:38.692 INFO [] Processing traceback with type server for None
2022-02-27 01:02:39.503 INFO [] Processing traceback with type server for None
2022-02-27 01:02:40.302 INFO [] Processing traceback with type server for None
2022-02-27 01:02:41.099 INFO [] Processing traceback with type server for None
2022-02-27 01:02:41.909 INFO [] Processing traceback with type server for None
2022-02-27 01:02:42.704 INFO [] Processing traceback with type server for None
2022-02-27 01:02:43.508 INFO [] Processing traceback with type server for None
2022-02-27 01:02:44.317 INFO [] Processing traceback with type server for None
2022-02-27 01:02:45.121 INFO [] Processing traceback with type server for None
2022-02-27 01:02:45.917 INFO [] Processing traceback with type server for None
2022-02-27 01:02:46.719 INFO [] Processing traceback with type server for None
2022-02-27 01:02:47.535 INFO [] Processing traceback with type server for None
2022-02-27 01:02:48.330 INFO [] Processing traceback with type server for None
2022-02-27 01:02:49.123 INFO [] Processing traceback with type server for None
2022-02-27 01:02:49.909 INFO [] Processing traceback with type server for None
2022-02-27 01:02:50.715 INFO [] Processing traceback with type server for None
2022-02-27 01:02:51.529 INFO [] Processing traceback with type server for None
2022-02-27 01:02:52.329 INFO [] Processing traceback with type server for None
2022-02-27 01:02:53.145 INFO [] Processing traceback with type server for None
2022-02-27 01:02:53.933 INFO [] Processing traceback with type server for None
2022-02-27 01:02:54.722 INFO [] Processing traceback with type server for None
2022-02-27 01:02:55.509 INFO [] Processing traceback with type server for None
2022-02-27 01:02:56.311 INFO [] Processing traceback with type server for None
2022-02-27 01:02:57.126 INFO [] Processing traceback with type server for None
2022-02-27 01:02:57.926 INFO [] Processing traceback with type server for None
2022-02-27 01:02:58.711 INFO [] Processing traceback with type server for None
2022-02-27 01:02:59.517 INFO [] Processing traceback with type server for None
2022-02-27 01:03:00.338 INFO [] Processing traceback with type server for None
2022-02-27 01:03:01.126 INFO [] Processing traceback with type server for None
2022-02-27 01:03:01.951 INFO [] Processing traceback with type server for None
2022-02-27 01:03:02.846 INFO [] Processing traceback with type server for None
2022-02-27 01:03:03.673 INFO [] Processing traceback with type server for None
2022-02-27 01:03:04.481 INFO [] Processing traceback with type server for None
2022-02-27 01:03:05.295 INFO [] Processing traceback with type server for None
2022-02-27 01:03:06.694 INFO [] Processing traceback with type server for None
2022-02-27 01:03:07.493 INFO [] Processing traceback with type server for None
2022-02-27 01:03:08.304 INFO [] Processing traceback with type server for None
2022-02-27 01:03:09.111 INFO [] Processing traceback with type server for None
2022-02-27 01:03:09.906 INFO [] Processing traceback with type server for None
2022-02-27 01:03:10.725 INFO [] Processing traceback with type server for None
2022-02-27 01:03:11.514 INFO [] Processing traceback with type server for None
2022-02-27 01:03:12.341 INFO [] Processing traceback with type server for None
2022-02-27 01:03:13.134 INFO [] Processing traceback with type server for None
2022-02-27 01:03:13.951 INFO [] Processing traceback with type server for None
2022-02-27 01:03:14.755 WARN [pika.channel] Received remote Channel.Close (406): 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f658c565280> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/home/zulip/deployments/2021-12-09-21-02-31/zerver/lib/queue.py", line 174, in do_consume
    channel.basic_ack(max_processed, multiple=True)
  File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 2112, in basic_ack
    self._flush_output()
  File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 1339, in _flush_output
    raise self._closing_reason  # pylint: disable=E0702
pika.exceptions.ChannelClosedByBroker: (406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/zulip/deployments/2021-12-09-21-02-31/zerver/management/commands/process_queue.py", line 105, in run
    self.worker.start()
  File "/home/zulip/deployments/2021-12-09-21-02-31/zerver/worker/queue_processors.py", line 396, in start
    self.q.start_json_consumer(
  File "/home/zulip/deployments/2021-12-09-21-02-31/zerver/lib/queue.py", line 183, in start_json_consumer
    self.ensure_queue(queue_name, do_consume)
  File "/home/zulip/deployments/2021-12-09-21-02-31/zerver/lib/queue.py", line 117, in ensure_queue
    callback(self.channel)
  File "/home/zulip/deployments/2021-12-09-21-02-31/zerver/lib/queue.py", line 176, in do_consume
    channel.basic_nack(max_processed, multiple=True)
  File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 2133, in basic_nack
    self._impl.basic_nack(
  File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/pika/channel.py", line 401, in basic_nack
    self._raise_if_not_open()
  File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/pika/channel.py", line 1393, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.


```
errors.log 

2022-02-28 09:15:25.607 ERR  [zulip.send_email] Error sending digest email to ['user-email']: Connection unexpectedly closed
Traceback (most recent call last):
  File "/home/zulip/deployments/2021-12-09-21-02-31/zerver/lib/send_email.py", line 254, in send_email
    if connection.send_messages([mail]) == 0:
  File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.8/smtplib.py", line 732, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.8/smtplib.py", line 635, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/lib/python3.8/smtplib.py", line 425, in docmd
    return self.getreply()
  File "/usr/lib/python3.8/smtplib.py", line 398, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
Stack (most recent call last):
  File "/home/zulip/deployments/current/manage.py", line 52, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/zulip/deployments/2021-12-09-21-02-31/zerver/management/commands/deliver_scheduled_emails.py", line 57, in handle
    deliver_scheduled_emails(job)
  File "/home/zulip/deployments/2021-12-09-21-02-31/zerver/lib/send_email.py", line 442, in deliver_scheduled_emails
    send_email(**data)
  File "/home/zulip/deployments/2021-12-09-21-02-31/zerver/lib/send_email.py", line 268, in send_email
    logger.exception(
2022-02-28 09:15:25.620 WARN [zerver.management.commands.deliver_scheduled_emails] <ScheduledEmail: <ScheduledEmail: 2 [<UserProfile: <UserProfile: user-email <Realm:  2>>>] 2021-11-09 18:00:11.538699+00:00>> not delivered
```

**Comment by timabbott** [comment]
OK, I think your problem is that RabbitMQ is not functional, which of course will break any queue workers.  It's hard for me to tell from that traceback why -- you'll need to dig in the logs for the first error, but one possibility is some sort of authentication or networking problem reaching the RabbitMQ node in your Docker setup. I don't think we can debug that efficiently over a GitHub issue, but you can try stopping by chat.zulip.org to investigate further.

**Comment by amolvishwakarma** [comment]
Hi @timabbott ,

Server storage issue happened this morning after increasing space I made the application up after that I got an email please can you let me know looking at the traces and what is the root cause for it.  

Logger django.request, from module django.utils.log line 224:
Error generated by Example User <[example@gmail.com](mailto:example@gmail.com)> (Member) on [zulip.example.com](http://zulip.example.com/) deployment

No stack trace available

Deployed code:
- git: None
- ZULIP_VERSION: 4.8


Request info:
- path: /json/users/me/presence
- POST: {'status': ['idle'], 'ping_only': ['false'], 'new_user_input': ['false'], 'slim_presence': ['true']}
- REMOTE_ADDR: "172.20.0.2"
- QUERY_STRING: ""
- SERVER_NAME: ""

**Comment by amolvishwakarma** [comment]
Hi @timabbott ,
Smokescreen is blocking push.zulipchat.com and some google domains.
Please guide me. 

Ref article: https://github.com/zulip/zulip/issues/20490

**Comment by amolvishwakarma** [comment]
Hi @timabbott, 

The issue is resolved SMTP is not working and the code is stuck in the loop to send digest email.

For a temporary fix removed all email process( zulip_deliver_scheduled_emails, zulip_events_digest_emails, zulip_events_email_mirror, zulip_events_email_senders, zulip_events_missedmessage_email) inside from /etc/supervisor/conf.d/zulip/zulip.conf

After that run supervisorctl update & restarted all the services using supervisorctl restart all.

Now all the workers are working as expected.

**Comment by alexmv** [comment]
https://github.com/zulip/zulip/issues/20490 is not relevant here, as all of those lines say `"allow":true` -- Smokescreen is very chatty in its logs, and those do not indicate failure.

Your failures with SMTP are likely related to SMTP authentication.  If you're interested in help debugging those further, please come discuss on [chat.zulip.org](https://chat.zulip.org/#narrow/stream/31-production-help).  Otherwise, I'm going to resolve this issue, since it seems to have been related to your local setup.
