### ISSUE TITLE
Database password authentication failed for user "zulip" after upgrade to 6.0

### ISSUE THREAD

**Issue by sjmgarnier** [zulip/docker-zulip#380]
I have upgraded to Zulip 6.0 following the instructions at https://github.com/zulip/docker-zulip/blob/main/UPGRADING.md, including upgrading to use Docker volumes and PostgreSQL 14. Since then, Zulip refuses to start again with the following error message: 

```
zulip_1      | === Begin Bootstrap Phase ===
zulip_1      | Waiting for database server to allow connections ...
zulip_1      | Executing Zulip first start init ...
zulip_1      | +++ readlink -f /home/zulip/deployments/current/scripts/setup/initialize-database
zulip_1      | ++ dirname /home/zulip/deployments/2022-12-07-16-14-22/scripts/setup/initialize-database
zulip_1      | + THIS_DIR=/home/zulip/deployments/2022-12-07-16-14-22/scripts/setup
zulip_1      | + cd /home/zulip/deployments/2022-12-07-16-14-22/scripts/setup/../..
zulip_1      | + ./manage.py checkconfig
zulip_1      | + ./manage.py migrate --noinput
zulip_1      | Traceback (most recent call last):
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
zulip_1      |     self.connect()
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
zulip_1      |     return func(*args, **kwargs)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 263, in connect
zulip_1      |     self.connection = self.get_new_connection(conn_params)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
zulip_1      |     return func(*args, **kwargs)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
zulip_1      |     connection = Database.connect(**conn_params)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
zulip_1      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
zulip_1      |   File "/home/zulip/deployments/2022-12-07-16-14-22/zerver/lib/db.py", line 48, in __init__
zulip_1      |     super().__init__(*args, **kwargs)
zulip_1      | psycopg2.OperationalError: connection to server at "database" (172.18.0.12), port 5432 failed: FATAL:  password authentication failed for user "zulip"
zulip_1      | 
zulip_1      | 
zulip_1      | The above exception was the direct cause of the following exception:
zulip_1      | 
zulip_1      | Traceback (most recent call last):
zulip_1      |   File "./manage.py", line 151, in <module>
zulip_1      |     execute_from_command_line(sys.argv)
zulip_1      |   File "./manage.py", line 116, in execute_from_command_line
zulip_1      |     utility.execute()
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
zulip_1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
zulip_1      |     self.execute(*args, **cmd_options)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
zulip_1      |     output = self.handle(*args, **options)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/base.py", line 96, in wrapped
zulip_1      |     res = handle_func(*args, **kwargs)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 114, in handle
zulip_1      |     executor = MigrationExecutor(connection, self.migration_progress_callback)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
zulip_1      |     self.loader = MigrationLoader(self.connection)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 58, in __init__
zulip_1      |     self.build_graph()
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 235, in build_graph
zulip_1      |     self.applied_migrations = recorder.applied_migrations()
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
zulip_1      |     if self.has_table():
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 57, in has_table
zulip_1      |     with self.connection.cursor() as cursor:
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
zulip_1      |     return func(*args, **kwargs)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 323, in cursor
zulip_1      |     return self._cursor()
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 299, in _cursor
zulip_1      |     self.ensure_connection()
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
zulip_1      |     return func(*args, **kwargs)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
zulip_1      |     self.connect()
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
zulip_1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
zulip_1      |     self.connect()
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
zulip_1      |     return func(*args, **kwargs)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 263, in connect
zulip_1      |     self.connection = self.get_new_connection(conn_params)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
zulip_1      |     return func(*args, **kwargs)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
zulip_1      |     connection = Database.connect(**conn_params)
zulip_1      |   File "/srv/zulip-venv-cache/7bce584675a91f5ea66d1f1814748fdac0d2084b/zulip-py3-venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
zulip_1      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
zulip_1      |   File "/home/zulip/deployments/2022-12-07-16-14-22/zerver/lib/db.py", line 48, in __init__
zulip_1      |     super().__init__(*args, **kwargs)
zulip_1      | django.db.utils.OperationalError: connection to server at "database" (172.18.0.12), port 5432 failed: FATAL:  password authentication failed for user "zulip"
zulip_1      | 
zulip_1      | Zulip first start database initi failed in "initialize-database" exit code 1. Exiting.
``` 

My docker-compose.yml reads like this: 

```
version: '2'
services:
  database:
    image: 'zulip/zulip-postgresql:14'
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'zulip'
      POSTGRES_USER: 'zulip'
      # Note that you need to do a manual `ALTER ROLE` query if you
      # change this on a system after booting the postgres container
      # the first time on a host.  Instructions are available in README.md.
      POSTGRES_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
    volumes:
      - 'postgresql-14:/var/lib/postgresql/data:rw'
  memcached:
    image: 'memcached:alpine'
    restart: unless-stopped
    command:
      - 'sh'
      - '-euc'
      - |
        echo 'mech_list: plain' > "$$SASL_CONF_PATH"
        echo "zulip@$$HOSTNAME:$$MEMCACHED_PASSWORD" > "$$MEMCACHED_SASL_PWDB"
        echo "zulip@localhost:$$MEMCACHED_PASSWORD" >> "$$MEMCACHED_SASL_PWDB"
        exec memcached -S
    environment:
      SASL_CONF_PATH: '/home/memcache/memcached.conf'
      MEMCACHED_SASL_PWDB: '/home/memcache/memcached-sasl-db'
      MEMCACHED_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
  rabbitmq:
    image: 'rabbitmq:3.7.7'
    restart: unless-stopped
    environment:
        RABBITMQ_DEFAULT_USER: 'zulip'
        RABBITMQ_DEFAULT_PASS: 'XXXXXXXXXXXXXXXXXXXXXXXX'
    volumes:
      - 'rabbitmq:/var/lib/rabbitmq:rw'
  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    command:
      - 'sh'
      - '-euc'
      - |
        echo "requirepass '$$REDIS_PASSWORD'" > /etc/redis.conf
        exec redis-server /etc/redis.conf
    environment:
      REDIS_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
    volumes:
      - 'redis:/data:rw'
  zulip:
    image: 'zulip/docker-zulip:6.0-0'
    restart: unless-stopped
    build:
      context: .
      args:
        # Change these if you want to build zulip from a different repo/branch
        ZULIP_GIT_URL: https://github.com/zulip/zulip.git
        ZULIP_GIT_REF: '6.0'
        # Set this up if you plan to use your own CA certificate bundle for building
        # CUSTOM_CA_CERTIFICATES:
    # ports:
      # - '80:80'
      # - '443:443'
    environment:
      VIRTUAL_HOST: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      VIRTUAL_PROTO: 'https'
      VIRTUAL_PORT: '443'
      LETSENCRYPT_HOST: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      LETSENCRYPT_EMAIL: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      DB_HOST: 'database'
      DB_HOST_PORT: '5432'
      DB_USER: 'zulip'
      SSL_CERTIFICATE_GENERATION: 'certbot'
      SETTING_MEMCACHED_LOCATION: 'memcached:11211'
      SETTING_RABBITMQ_HOST: 'rabbitmq'
      SETTING_REDIS_HOST: 'redis'
      SECRETS_email_password: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      # These should match RABBITMQ_DEFAULT_PASS, POSTGRES_PASSWORD,
      # MEMCACHED_PASSWORD, and REDIS_PASSWORD above.
      SECRETS_rabbitmq_password: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      SECRETS_postgres_password: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      SECRETS_memcached_password: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      SECRETS_redis_password: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      SECRETS_secret_key: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      SETTING_EXTERNAL_HOST: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      SETTING_ZULIP_ADMINISTRATOR: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      SETTING_EMAIL_HOST: 'smtp.sendgrid.net'
      SETTING_EMAIL_HOST_USER: 'apikey'
      SETTING_EMAIL_PORT: '465'
      # It seems that the email server needs to use ssl or tls and can't be used without it
      SETTING_EMAIL_USE_SSL: 'True'
      SETTING_EMAIL_USE_TLS: 'False'
      SETTING_ADD_TOKENS_TO_NOREPLY_ADDRESS: 'False'
      SETTING_NOREPLY_EMAIL_ADDRESS: 'XXXXXXXXXXXXXXXXXXXXXXXX'
      ZULIP_AUTH_BACKENDS: 'EmailAuthBackend'
      # Uncomment this when configuring the mobile push notifications service
      SETTING_PUSH_NOTIFICATION_BOUNCER_URL: 'https://push.zulipchat.com'
    volumes:
      - 'zulip:/data:rw'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1048576
volumes:
  zulip:
  postgresql-14:
  rabbitmq:
  redis:
networks:
  default:
    external:
      name: nginx-proxy
```

Note that I didn't change any of the passwords during the upgrade. Thanks in advance for your help.

**Comment by sjmgarnier** [comment]
The problem was caused by the PostgreSQL upgrade script that didn't complete properly. A manual upgrade of PostgreSQL did the trick.
