### ISSUE TITLE
Unable to configure S3

### ISSUE THREAD

**Issue by arladmin** [zulip/docker-zulip#386]
After setting all the necessary config variables, as instructed here https://zulip.readthedocs.io/en/stable/production/upload-backends.html#s3-backend-configuration, for my DigitalOcean Spaces bucket, i'm getting this error:

```
root@7ae3983abfbb:/# crudini --set /etc/zulip/zulip.conf application_server no_serve_uploads true
root@7ae3983abfbb:/# /home/zulip/deployments/current/scripts/zulip-puppet-apply

Notice: Compiled catalog for 7ae3983abfbb in environment production in 1.38 seconds
Notice: Applied catalog in 0.42 seconds
root@7ae3983abfbb:/# 
root@7ae3983abfbb:/# su zulip
zulip@7ae3983abfbb:/$ /home/zulip/deployments/current/scripts/restart-server
2023-02-15 08:04:09,810 restart-server: Running syntax and database checks
Traceback (most recent call last):
  File "./manage.py", line 145, in <module>
    log_management_command(sys.argv, settings.MANAGEMENT_LOG_PATH)
  File "/srv/zulip-venv-cache/b2cdd20dd55ad18cd1e512082a3ec530e6b6ece9/zulip-py3-venv/lib/python3.8/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/srv/zulip-venv-cache/b2cdd20dd55ad18cd1e512082a3ec530e6b6ece9/zulip-py3-venv/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/srv/zulip-venv-cache/b2cdd20dd55ad18cd1e512082a3ec530e6b6ece9/zulip-py3-venv/lib/python3.8/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zulip/deployments/2023-01-23-18-51-59/zproject/settings.py", line 27, in <module>
    from .computed_settings import *  # noqa: F403 isort: skip
  File "/home/zulip/deployments/2023-01-23-18-51-59/zproject/computed_settings.py", line 75, in <module>
    SECRET_KEY = get_mandatory_secret("secret_key")
  File "/home/zulip/deployments/2023-01-23-18-51-59/zproject/config.py", line 50, in get_mandatory_secret
    raise ZulipSettingsError(f'Mandatory secret "{key}" is not set')
zproject.config.ZulipSettingsError: Mandatory secret "secret_key" is not set
Traceback (most recent call last):
  File "/home/zulip/deployments/current/scripts/restart-server", line 47, in <module>
    subprocess.check_call(["./manage.py", "check", "--database", "default"])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./manage.py', 'check', '--database', 'default']' returned non-zero exit status 1.
zulip@7ae3983abfbb:/$
```

**Comment by arladmin** [comment]
Kindly advise a resolution/workaround for this issue.

Thanks.

**Comment by alexmv** [comment]
```
zproject.config.ZulipSettingsError: Mandatory secret "secret_key" is not set
```

This says that `/etc/zulip/zulip-secrets.conf` is missing, unreadable, or has had some important lines removed.  When you added `s3_key` and `s3_secret_key`, did you remove any of the existing lines?

**Comment by mateuszmandera** [comment]
This seems to have just been an issue with the file were the keys were being configured, so I'll go ahead and close (ref https://chat.zulip.org/#narrow/stream/31-production-help/topic/S3.20config.20is.20failing)
