### ISSUE TITLE
Traefik as a Reverse Proxy with Docker Swarm

### ISSUE THREAD

**Issue by leadvic** [zulip/docker-zulip#420]
Hi there,
I'm having some issue trying to get Zulip working with my Traefik configuration.

This is my Zulip configuration on the docker compose:

```
  zulip:
    image: zulip/docker-zulip:7.5-0
    environment:
      DB_HOST: "database"
      DB_HOST_PORT: "5432"
      DB_USER: "zulip"
      SSL_CERTIFICATE_GENERATION: "self-signed"
      SETTING_MEMCACHED_LOCATION: "memcached:11211"
      SETTING_RABBITMQ_HOST: "rabbitmq"
      SETTING_REDIS_HOST: "redis"
      SECRETS_email_password: "123456789"
      # These should match RABBITMQ_DEFAULT_PASS, POSTGRES_PASSWORD,
      # MEMCACHED_PASSWORD, and REDIS_PASSWORD above.
      SECRETS_rabbitmq_password: "REPLACE_WITH_SECURE_RABBITMQ_PASSWORD"
      SECRETS_postgres_password: "REPLACE_WITH_SECURE_POSTGRES_PASSWORD"
      SECRETS_memcached_password: "REPLACE_WITH_SECURE_MEMCACHED_PASSWORD"
      SECRETS_redis_password: "REPLACE_WITH_SECURE_REDIS_PASSWORD"
      SECRETS_secret_key: "REPLACE_WITH_SECURE_SECRET_KEY"
      SETTING_EXTERNAL_HOST: "zulip.custom.domain"
      SETTING_ZULIP_ADMINISTRATOR: "myemail@email.com"
      SETTING_EMAIL_HOST: "" # e.g. smtp.example.com
      SETTING_EMAIL_HOST_USER: "noreply@example.com"
      SETTING_EMAIL_PORT: "587"
      # It seems that the email server needs to use ssl or tls and can't be used without it
      SETTING_EMAIL_USE_SSL: "False"
      SETTING_EMAIL_USE_TLS: "True"
      ZULIP_AUTH_BACKENDS: "EmailAuthBackend"
      DISABLE_HTTPS: "True"
      SETTING_ALLOWED_HOSTS: "['zulip.custom.domain','127.0.0.1','10.0.7.173']"
      SETTING_USE_X_FORWARDED_HOST: "True"
      # Uncomment this when configuring the mobile push notifications service
      # SETTING_PUSH_NOTIFICATION_BOUNCER_URL: 'https://push.zulipchat.com'
    volumes:
      - "zulip:/data:rw"
    networks:
      - zulip
      - traefik
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.zulip.entrypoints: websecure
        traefik.http.routers.zulip.rule: Host(`zulip.custom.domain`)
        traefik.http.routers.zulip.tls.certresolver: letsencrypt
        traefik.http.services.zulip.loadbalancer.server.port: 80
```

Thanks to `DISABLE_HTTPS: "True"` I was able to get to Zulip with my custom domain. But now I encounter another issue, in Zulip webpage I receive this: **Internal server error** which recommends me to check this page: https://zulip.readthedocs.io/en/latest/production/troubleshooting.html

Following along I got to the error logs inside my container: /var/log/zulip/errors.log
And I receive this error:
```
2023-12-14 03:06:16.493 ERR  [django.request] Internal Server Error: /
Traceback (most recent call last):
  File "/srv/zulip-venv-cache/91891b485c66dcf1dcb5c01dcf020d982a39839d/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/srv/zulip-venv-cache/91891b485c66dcf1dcb5c01dcf020d982a39839d/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = middleware_method(
  File "/home/zulip/deployments/2023-11-17-14-00-06/./zerver/middleware.py", line 654, in process_view
    raise ProxyMisconfigurationError(proxy_state_header)
zerver.middleware.ProxyMisconfigurationError: Reverse proxy misconfiguration: No proxies configured in Zulip, but proxy headers detected from proxy at 10.0.7.173; see https://zulip.readthedocs.io/en/latest/production/deployment.html#putting-the-zulip-application-behind-a-reverse-proxy
```

Which makes no sense to me, as I already set in SETTING_ALLOWED_HOSTS the IP of my reverse proxy 10.0.7.173.
I think I might be missing something here, I'm kind of lost.

**Comment by schewara** [comment]
@leadvic 

I think this is the page you are looking for:

- https://github.com/zulip/docker-zulip/wiki/Proxying-via-nginx-on-host-machine

Setting either the Docker network subnet mask or the fixed IP of traefik in the container network should do the trick. (which would be the `traefik` network I guess)

`LOADBALANCER_IPS: "172.1x.0.0/16"`


The `ALLOWED_HOSTS` setting only defines additional hostnames which you can use to access zulip and which will prob. fail with an TLS Error as the let's encrypt certificate only contains the hostname, unless you access zulip directly without traefik.

see also:

- https://github.com/zulip/zulip/blob/940c2a1dedd79c30b1203d585ed78afb17da79c6/zproject/prod_settings_template.py#L43

**Comment by leadvic** [comment]
Awesome @schewara, that was exactly what I needed, thank you so much for your help.
I have added `LOADBALANCER_IPS` and modified `ALLOWED_HOSTS` as you recommeded, and it works just fine!

Thank you once again!
