### ISSUE TITLE
Rocket.Chat migration error 'list index out of range' during data convertation

### ISSUE THREAD

**Issue by someadmin** [zulip/docker-zulip#438]
Hello!
I got an error, trying to convert data exported from rocketchat with **mongodump -o "path"** command inside the zulip container:

zulip@cec005526bd0:~/deployments/current$ ./manage.py convert_rocketchat_data /tmp/dump/rocketchat/ --output /tmp/converted_rocketchat_data
Converting Data ...
Traceback (most recent call last):
File "./manage.py", line 157, in
execute_from_command_line(sys.argv)
File "./manage.py", line 122, in execute_from_command_line
utility.execute()
File "/srv/zulip-venv-cache/726c7d1d35d9cd61bb4b70e98167a1db7b0c524d/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/init.py", line 413, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/srv/zulip-venv-cache/726c7d1d35d9cd61bb4b70e98167a1db7b0c524d/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
self.execute(*args, **cmd_options)
File "/srv/zulip-venv-cache/726c7d1d35d9cd61bb4b70e98167a1db7b0c524d/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
output = self.handle(*args, **options)
File "/home/zulip/deployments/2022-03-29-17-46-36/zerver/management/commands/convert_rocketchat_data.py", line 45, in handle
do_convert_data(rocketchat_data_dir=data_dir, output_dir=output_dir)
File "/home/zulip/deployments/2022-03-29-17-46-36/zerver/data_import/rocketchat.py", line 940, in do_convert_data
realm = make_realm(realm_id, realm_subdomain, domain_name, rocketchat_data["instance"][0])
**IndexError: list index out of range**

Initially after **mongodump -o /tmp/dump** i got 3 folders in "**dump**", and one of them is "**rocketchat**", that obviously contains rocketchat data as .bson files.

Currently i'm trying this with MongoDB v6.0.4 dump of Rocket.Chat v6.4.7 and docker-composed  Zulip v 8.3**** but also tried Zulip versions 6.0 and 7.0, and earlier Rocket.Chat releases till 6.4.2.

Can anyone, please, clarify is it my fault during mongodump or convertion script bug?

**Comment by timabbott** [comment]
Zulip 9.0 fixed most of the known Rocket.Chat data import bugs; I can't tell if this is one of them from that exception, but please report on zulip/zulip if it doesn't work for you (or anyone else reading this) on the latest release.
